// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Kanban.Collector.Core.Data;

#nullable disable

namespace Kanban.Collector.Core.Data.Migrations.DataSourceSnapshots
{
    [DbContext(typeof(DataSourceSnapshotDbContext))]
    [Migration("20260817120000_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Kanban.Collector.Core.Entities.DataSourceSnapshotRecord", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("DeviceId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsValid")
                    .HasColumnType("INTEGER");

                b.Property<string>("ShiftName")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("SourceId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("SourceName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("SourceType")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("TEXT");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<int>("Value")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("DeviceId");

                b.HasIndex("DeviceId", "Timestamp");

                b.HasIndex("SourceId", "Timestamp");

                b.HasIndex("Timestamp");

                b.ToTable("DataSourceSnapshots");
            });
#pragma warning restore 612, 618
        }
    }
}