<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>PlcSimulator</RootNamespace>
    <AssemblyName>PlcSimulator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PlcSimulator.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HslCommunication">
      <HintPath>..\lib\HslCommunication\HslCommunication.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kanban.Contracts\Kanban.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>

</Project>
