#!/usr/bin/env python3
"""
Generate Kanban.Web/Localization.cs from WPF Strings.resx (zh/en/ja).

Usage: python ci/generate_web_loc.py
       python ci/generate_web_loc.py --check   (CI mode)

Reads: MainAPP/Resources/Strings.resx + Strings.en.resx + Strings.ja.resx
Generates: Kanban.Web/Localization.cs

The generated file contains all Web_* keys (prefix stripped) plus shared
keys (Conn_*, Status_*, etc.) as `new[] { "zh", "en", "ja" }` arrays.
Missing keys fall back to the key name itself (visible in UI for troubleshooting).
"""

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RESX_ZH = PROJECT_ROOT / "MainAPP" / "Resources" / "Strings.resx"
RESX_EN = PROJECT_ROOT / "MainAPP" / "Resources" / "Strings.en.resx"
RESX_JA = PROJECT_ROOT / "MainAPP" / "Resources" / "Strings.ja.resx"
WEB_LOC = PROJECT_ROOT / "Kanban.Web" / "Localization.cs"

# Web 端直接使用的共享 resx key（非 Web_ 前缀，与 resx 同名——Web key 命名与 WPF resx 完全一致，
# 无需映射表。新增 Web 文案优先用 Web_ 前缀 key；需要复用 WPF 共享文案时在此白名单登记同名 key）。
SHARED_KEYS = [
    "Badge_Recent1Min", "Card_Alarms", "Card_DevCount", "Card_DevStatus", "Card_Oee",
    "Card_Output", "Card_ProdStatus", "Card_Shift", "Card_Source", "Card_Trend",
    "Card_WorkOrder", "Conn_Connected", "Conn_Disconnected", "Conn_Live", "Fresh_Live", "Fresh_Mins",
    "Fresh_None", "Fresh_Secs", "Lbl_Achievement", "Lbl_ActualCycle", "Lbl_Availability",
    "Lbl_ConnStatus", "Lbl_DataFresh", "Lbl_DevTotal", "Lbl_Elapsed", "Lbl_Ng",
    "Lbl_NgRate", "Lbl_Ok", "Lbl_Performance", "Lbl_Planned", "Lbl_Quality",
    "Lbl_RealTimeSpeed", "Lbl_Remaining", "Lbl_SnapSeq", "Lbl_SvcAddr", "Lbl_SvcVersion",
    "Lbl_TargetCycle", "Lbl_TotalOutput", "Meta_PlanWo", "Meta_QualityRate", "Meta_ShiftAuto",
    "Meta_StatusWord", "Meta_TrendCurrent", "Msg_EmptyHint", "Msg_NoDevSelected",
    "Msg_NoDeviceData", "Msg_SelectHint", "Msg_WaitingConn", "Status_Alarm", "Status_Idle",
    "Status_Paused", "Status_Running", "Val_DynAddr", "Val_NoAlarms", "Val_NoWorkOrder",
    "Val_WaitData", "Wo_Aborted", "Wo_Completed", "Wo_Pending", "Wo_Progress",
    "Wo_ProgressPending", "Wo_Running",
]


def parse_resx(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    result = {}
    for m in re.finditer(r'<data name="(\w+)"[^>]*>\s*<value>([^<]*)</value>', text, re.S):
        result[m.group(1)] = m.group(2)
    return result


def csharp_escape(s: str) -> str:
    """Escape for C# double-quoted string."""
    return s.replace('\\', '\\\\').replace('"', '\\"')


def resolve_key(key: str, zh: dict, en: dict, ja: dict) -> tuple[str, str, str]:
    """Resolve a Web key to (zh, en, ja) values from resx. Fallback = key name."""
    # 1. Web_{key}
    full = f"Web_{key}"
    if full in zh:
        return (zh[full], en.get(full, key), ja.get(full, key))
    # 2. 直接查找（共享 key，如 Conn_Live / Status_Running）
    if key in zh:
        return (zh[key], en.get(key, key), ja.get(key, key))
    # 3. Fallback = key 名本身（便于排查漏翻译）
    return (key, key, key)


def collect_keys(zh: dict, existing_template: str | None) -> list[str]:
    """Collect all Web keys to emit. Source of truth = WPF resx:
    Web_* prefixed keys (prefix stripped) + SHARED_KEYS (same-name shared keys)."""
    keys = set()
    # 1. All Web_* keys (strip prefix)
    for full_key in zh:
        if full_key.startswith("Web_"):
            keys.add(full_key[4:])
    # 2. Shared keys used directly by the Web UI (same name as resx)
    keys.update(SHARED_KEYS)
    return sorted(keys)


def generate():
    zh = parse_resx(RESX_ZH)
    en = parse_resx(RESX_EN)
    ja = parse_resx(RESX_JA)

    old_template = WEB_LOC.read_text(encoding="utf-8") if WEB_LOC.exists() else None
    keys = collect_keys(zh, old_template)

    entries = []
    for key in keys:
        zh_val, en_val, ja_val = resolve_key(key, zh, en, ja)
        entries.append(
            f'        ["{key}"] = new[] {{ "{csharp_escape(zh_val)}", '
            f'"{csharp_escape(en_val)}", "{csharp_escape(ja_val)}" }},'
        )

    output = f'''namespace Kanban.Web;

/// <summary>屏端界面语言（与 Kanban.Core.Services.AppLanguage 值对齐：0=中文/1=English/2=日本語）。</summary>
public enum WebLanguage
{{
    Zh = 0,
    En = 1,
    Ja = 2,
}}

/// <summary>
/// WASM 屏端多语言字典（zh/en/ja 三语内嵌）。
/// WARNING: AUTO-GENERATED by ci/generate_web_loc.py. DO NOT EDIT MANUALLY.
/// All {len(keys)} keys from WPF Strings.resx (single source of truth).
/// To add/change text: edit WPF Strings.resx Web_* keys, then run "python ci/generate_web_loc.py".
/// CI guard (LocalizationGuardTests) verifies no template placeholders remain.
/// </summary>
public static class L
{{
    private static readonly Dictionary<string, string[]> D = new()
    {{
{chr(10).join(entries)}
    }};

    public static WebLanguage Current {{ get; set; }} = WebLanguage.Zh;

    public static string T(string key, params object[] args)
    {{
        if (D.TryGetValue(key, out var v))
        {{
            var s = v[(int)Current];
            return args.Length > 0 ? string.Format(s, args) : s;
        }}
        return key;
    }}
}}
'''

    old = WEB_LOC.read_text(encoding="utf-8") if WEB_LOC.exists() else ""
    if old.strip() == output.strip():
        print(f"Localization.cs is up-to-date ({len(keys)} keys)")
        return

    WEB_LOC.write_text(output, encoding="utf-8")
    print(f"Generated {WEB_LOC} — {len(keys)} keys from WPF resx")


def check():
    """CI mode: verify Localization.cs matches generated output."""
    old = WEB_LOC.read_text(encoding="utf-8") if WEB_LOC.exists() else ""
    generate()
    new = WEB_LOC.read_text(encoding="utf-8")
    if old.strip() != new.strip():
        print("ERROR: Kanban.Web/Localization.cs is out of date!", file=sys.stderr)
        print("Run: python ci/generate_web_loc.py", file=sys.stderr)
        sys.exit(1)
    print("OK: Kanban.Web/Localization.cs is up-to-date")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        check()
    else:
        generate()
