#!/usr/bin/env python3
"""
Generate MainAPP/Resources/Strings.cs from WPF Strings.resx.

Usage: python ci/generate_wpf_strings.py

Reads: MainAPP/Resources/Strings.resx (zh — single source of truth)
Generates: MainAPP/Resources/Strings.cs

The generated Strings.cs has zero inline Chinese text. Every property
fallback is the key name itself, so missing resx keys are immediately
visible in the UI as the key name rather than stale Chinese.
"""

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RESX_ZH = PROJECT_ROOT / "MainAPP" / "Resources" / "Strings.resx"
STRINGS_CS = PROJECT_ROOT / "MainAPP" / "Resources" / "Strings.cs"


def parse_resx(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    result = {}
    for m in re.finditer(r'<data name="(\w+)"[^>]*>\s*<value>([^<]*)</value>', text, re.S):
        result[m.group(1)] = m.group(2)
    return result


def generate():
    zh = parse_resx(RESX_ZH)

    # Filter system keys
    system_keys = {"resmimetype", "reader", "writer", "version"}
    keys = sorted(k for k in zh if k not in system_keys)

    prop_lines = []
    for k in keys:
        # Fallback = key name (no Chinese duplication). Missing resx → shows key name in UI.
        prop_lines.append(f'        public static string {k} => S("{k}", "{k}");')

    output = f'''using System.Globalization;
using System.Resources;

namespace MainAPP.Resources;

/// <summary>
/// 多语言资源强类型访问（中文默认 / 英文 / 日文）。
/// WARNING: AUTO-GENERATED by ci/generate_wpf_strings.py. DO NOT EDIT MANUALLY.
/// All {len(keys)} keys from Strings.resx (single source of truth).
/// To add/change text: edit Strings.resx + Strings.en.resx + Strings.ja.resx,
/// then run "python ci/generate_wpf_strings.py".
/// </summary>
public static class Strings
{{
    private static readonly ResourceManager Res = new("MainAPP.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>
    /// 启动时由 Localization.Apply 一次性捕获的 UI 文化（en-US / zh-CN / ja-JP）。
    /// 统一用启动期捕获的稳定文化，所有 {{x:Static}}、ViewModel 字段初始化器、计算属性
    /// 全部读到同一份翻译——避免英文模式下 UI 残留中文。
    /// </summary>
    private static CultureInfo s_capturedCulture = CultureInfo.GetCultureInfo("zh-CN");

    public static void CaptureCulture(CultureInfo culture)
    {{
        s_capturedCulture = culture;
    }}

    /// <summary>按启动期捕获的 UI 文化取资源；缺失时回退 key 名本身（便于排查漏翻译）。</summary>
    public static string S(string key, string fallback)
        => Res.GetString(key, s_capturedCulture) ?? fallback;

{chr(10).join(prop_lines)}
}}
'''

    old = STRINGS_CS.read_text(encoding="utf-8") if STRINGS_CS.exists() else ""
    if old.strip() == output.strip():
        print(f"Strings.cs is up-to-date ({len(keys)} keys)")
        return

    STRINGS_CS.write_text(output, encoding="utf-8")
    print(f"Generated {STRINGS_CS} — {len(keys)} keys from Strings.resx")


def check():
    """CI mode: verify Strings.cs matches generated output."""
    import tempfile
    old = STRINGS_CS.read_text(encoding="utf-8")
    generate()
    new = STRINGS_CS.read_text(encoding="utf-8")
    if old.strip() != new.strip():
        print("ERROR: Strings.cs is out of date!", file=sys.stderr)
        print("Run: python ci/generate_wpf_strings.py", file=sys.stderr)
        sys.exit(1)
    print("OK: Strings.cs is up-to-date")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        check()
    else:
        generate()
