using System.Globalization;
using Kanban.Contracts.Dtos;

namespace Kanban.Web;

/// <summary>屏端语言代码常量。新增语言由 Localization.csv 表头自动加入运行时目录。</summary>
public static class WebLanguage
{
    public const string zh_CN = "zh-CN";
    public const string en_US = "en-US";
    public const string ja_JP = "ja-JP";
    public const string pt_BR = "pt-BR";
}

/// <summary>
/// WASM 屏端多语言字典（语言代码由 Localization.csv 表头定义）。
/// WARNING: AUTO-GENERATED by ci/generate_localization.py. DO NOT EDIT MANUALLY.
/// All 464 keys are derived from Localization.csv Wpf rows.
/// </summary>
public static class L
{
    private static readonly Dictionary<string, string[]> BuiltinD = new()
    {
        ["Ac_ActiveCount"] = new[] { "当前活跃", "Active Alarms", "現在の警報", "Alarmes ativos" },
        ["Ac_ActiveTitle"] = new[] { "实时活跃报警", "Live Active Alarms", "リアルタイム警報", "Alarmes ativos em tempo real" },
        ["Ac_AffectedDevices"] = new[] { "涉及设备", "Devices Affected", "影響デバイス", "Dispositivos afetados" },
        ["Ac_AlarmName"] = new[] { "报警名称", "Alarm Name", "アラーム名", "Nome do alarme" },
        ["Ac_Count"] = new[] { "次数", "Count", "回数", "Contagem" },
        ["Ac_Device"] = new[] { "设备", "Device", "デバイス", "Dispositivo" },
        ["Ac_Level"] = new[] { "级别", "Level", "レベル", "Nível" },
        ["Ac_LevelHigh"] = new[] { "高", "High", "高", "Alto" },
        ["Ac_LevelLow"] = new[] { "低", "Low", "低", "Baixo" },
        ["Ac_LevelMedium"] = new[] { "中", "Medium", "中", "Médio" },
        ["Ac_Longest"] = new[] { "最长持续", "Longest Active", "最長継続", "Maior duração ativa" },
        ["Ac_Range1h"] = new[] { "近 1 小时", "Last 1 Hour", "直近1時間", "Última 1 hora" },
        ["Ac_Range24h"] = new[] { "近 24 小时", "Last 24 Hours", "直近24時間", "Últimas 24 horas" },
        ["Ac_Range4h"] = new[] { "近 4 小时", "Last 4 Hours", "直近4時間", "Últimas 4 horas" },
        ["Ac_Rank"] = new[] { "排名", "Rank", "順位", "Posição" },
        ["Ac_RecentTitle"] = new[] { "最近事件", "Recent Events", "最近のイベント", "Eventos recentes" },
        ["Ac_StatsTitle"] = new[] { "报警统计", "Alarm Statistics", "警報統計", "Estatísticas de alarmes" },
        ["Ac_TodayRecover"] = new[] { "今日恢复", "Today Recovered", "今日の復旧", "Recuperados hoje" },
        ["Ac_TodayTrigger"] = new[] { "今日触发", "Today Triggered", "今日の発生", "Disparados hoje" },
        ["Ac_TopTitle"] = new[] { "触发次数 Top 10", "Trigger Count Top 10", "トリガー回数 TOP 10", "Top 10 por disparos" },
        ["Ac_TotalDuration"] = new[] { "累计时长", "Total Duration", "累計時間", "Duração acumulada" },
        ["App_Title"] = new[] { "生产看板", "Production Dashboard", "生産ダッシュボード", "Painel de Produção" },
        ["Au_Action"] = new[] { "操作类型", "Action", "操作種別", "Tipo de ação" },
        ["Au_ActionHint"] = new[] { "如 Device.Update", "e.g. Device.Update", "例: Device.Update", "ex.: Device.Update" },
        ["Au_AllResults"] = new[] { "全部结果", "All Results", "全結果", "Todos os resultados" },
        ["Au_Detail"] = new[] { "详情", "Detail", "詳細", "Detalhes" },
        ["Au_Failed"] = new[] { "失败", "Failed", "失敗", "Falha" },
        ["Au_List"] = new[] { "审计记录", "Audit Records", "監査記録", "Registros de auditoria" },
        ["Au_None"] = new[] { "暂无审计记录", "No audit records", "監査記録なし", "Sem registros de auditoria" },
        ["Au_Operator"] = new[] { "操作人", "Operator", "操作者", "Operador" },
        ["Au_OperatorHint"] = new[] { "如 Remote / admin", "e.g. Remote / admin", "例: Remote / admin", "ex.: Remote / admin" },
        ["Au_Result"] = new[] { "结果", "Result", "結果", "Resultado" },
        ["Au_Success"] = new[] { "成功", "Success", "成功", "Sucesso" },
        ["Au_TargetId"] = new[] { "对象 ID", "Target ID", "対象 ID", "ID do objeto" },
        ["Au_TargetType"] = new[] { "对象类型", "Target Type", "対象種別", "Tipo de objeto" },
        ["Au_Title"] = new[] { "审计查询（只读）", "Audit Log (Read-only)", "監査ログ（読み取り専用）", "Log de auditoria (somente leitura)" },
        ["Badge_Recent1Min"] = new[] { "近 1 分钟", "Last 1 min", "直近1分", "Último minuto" },
        ["Card_Alarms"] = new[] { "实时故障", "Live Alarms", "リアルタイム故障", "Alarmes em tempo real" },
        ["Card_DevCount"] = new[] { "设备总数", "Total Devices", "デバイス総数", "Total de dispositivos" },
        ["Card_DevStatus"] = new[] { "设备状态", "Device Status", "設備状態", "Status dos dispositivos" },
        ["Card_Oee"] = new[] { "OEE设备综合使用效率", "OEE Overall Equipment Effectiveness", "OEE設備総合使用効率", "OEE eficiência geral de uso do equipamento" },
        ["Card_Output"] = new[] { "产量明细", "Output Details", "生産明細", "Detalhes de produção" },
        ["Card_ProdStatus"] = new[] { "当前生产进度状态", "Current Production Progress", "現在の生産進捗状態", "Progresso da produção atual" },
        ["Card_Shift"] = new[] { "班次进度", "Shift Progress", "シフト進捗", "Progresso do turno" },
        ["Card_Source"] = new[] { "数据源", "Data Source", "データソース", "Fonte de dados" },
        ["Card_Trend"] = new[] { "速度趋势", "Speed Trend", "速度トレンド", "Tendência de velocidade" },
        ["Card_WorkOrder"] = new[] { "当前工单", "Current Work Order", "現在の工単", "Ordem de produção atual" },
        ["ConnLost"] = new[] { "连接中断，正在重连…", "Connection lost, reconnecting…", "接続が切れました。再接続中…", "Conexão perdida, reconectando…" },
        ["ConnStale"] = new[] { "数据停滞 {0}s，采集服务可能卡死", "Data stalled for {0}s; the collection service may be stuck", "データが {0}s 停滞しています。収集サービスが停止している可能性があります", "Dados parados há {0}s; o serviço de coleta pode estar travado" },
        ["Conn_Connected"] = new[] { "已连接", "Connected", "接続済み", "Conectado" },
        ["Conn_Disconnected"] = new[] { "未连接", "Disconnected", "未接続", "Desconectado" },
        ["Conn_Live"] = new[] { "实时", "Live", "リアルタイム", "Em tempo real" },
        ["Csv_AlarmId"] = new[] { "报警ID", "Alarm ID", "アラームID", "ID do alarme" },
        ["Csv_AlarmName"] = new[] { "报警名称", "Alarm Name", "アラーム名", "Nome do alarme" },
        ["Csv_AlarmSeconds"] = new[] { "报警时长(s)", "Alarm Time (s)", "アラーム時間(s)", "Tempo de alarme (s)" },
        ["Csv_CurrState"] = new[] { "当前状态", "Current State", "現在状態", "Estado atual" },
        ["Csv_CurrStateText"] = new[] { "当前状态文本", "Current State Text", "現在状態テキスト", "Texto do estado atual" },
        ["Csv_DeviceId"] = new[] { "设备ID", "Device ID", "設備ID", "ID do dispositivo" },
        ["Csv_DeviceName"] = new[] { "设备名称", "Device Name", "設備名", "Nome do dispositivo" },
        ["Csv_EventTime"] = new[] { "事件时间", "Event Time", "イベント時刻", "Hora do evento" },
        ["Csv_EventType"] = new[] { "事件类型", "Event Type", "イベント種別", "Tipo de evento" },
        ["Csv_EventTypeText"] = new[] { "事件类型文本", "Event Type Text", "イベント種別テキスト", "Texto do tipo de evento" },
        ["Csv_FileAlarm"] = new[] { "报警_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "alarms_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "alarms_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "alarmes_{0:yyyyMMdd}_{1:yyyyMMdd}.csv" },
        ["Csv_FileProd"] = new[] { "产量_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "production_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "production_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "producao_{0:yyyyMMdd}_{1:yyyyMMdd}.csv" },
        ["Csv_FileStatus"] = new[] { "状态时长_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "status_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "status_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "duracao_estado_{0:yyyyMMdd}_{1:yyyyMMdd}.csv" },
        ["Csv_Metric"] = new[] { "指标", "Metric", "指標", "Métrica" },
        ["Csv_NgCount"] = new[] { "NG产量", "NG Output", "NG生産数", "Produção NG" },
        ["Csv_OkCount"] = new[] { "OK产量", "OK Output", "OK生産数", "Produção OK" },
        ["Csv_PlcAddress"] = new[] { "PLC地址", "PLC Address", "PLCアドレス", "Endereço PLC" },
        ["Csv_PrevState"] = new[] { "前一状态", "Previous State", "前回状態", "Estado anterior" },
        ["Csv_PrevStateText"] = new[] { "前一状态文本", "Previous State Text", "前回状態テキスト", "Texto do estado anterior" },
        ["Csv_RunSeconds"] = new[] { "运行时长(s)", "Run Time (s)", "稼働時間(s)", "Tempo de execução (s)" },
        ["Csv_Shift"] = new[] { "班次", "Shift", "シフト", "Turno" },
        ["Csv_StatusWord"] = new[] { "状态字", "Status Word", "ステータスワード", "Palavra de status" },
        ["Csv_SumAlarm"] = new[] { "# 触发：{0} 次，恢复：{1} 次，待恢复：{2} 条", "# Triggered: {0}, Recovered: {1}, Pending: {2}", "# 発報：{0} 回、復旧：{1} 回、未復旧：{2} 件", "# Disparados: {0}, Recuperados: {1}, Pendentes: {2}" },
        ["Csv_SumDevice"] = new[] { "# 设备：{0}", "# Device: {0}", "# 設備：{0}", "# Dispositivo: {0}" },
        ["Csv_SumProd"] = new[] { "# 总 OK：{0} 件，总 NG：{1} 件，良品率：{2}", "# Total OK: {0}, Total NG: {1}, Yield: {2}", "# OK合計：{0} 個、NG合計：{1} 個、良品率：{2}", "# Total OK: {0}, Total NG: {1}, Rendimento: {2}" },
        ["Csv_SumRange"] = new[] { "# 查询区间：{0:yyyy-MM-dd HH:mm:ss} ~ {1:yyyy-MM-dd HH:mm:ss}", "# Range: {0:yyyy-MM-dd HH:mm:ss} ~ {1:yyyy-MM-dd HH:mm:ss}", "# 照会範囲：{0:yyyy-MM-dd HH:mm:ss} ~ {1:yyyy-MM-dd HH:mm:ss}", "# Intervalo: {0:yyyy-MM-dd HH:mm:ss} ~ {1:yyyy-MM-dd HH:mm:ss}" },
        ["Csv_SumStatus"] = new[] { "# 运行时长：{0}h，报警时长：{1}h，待机时长：{2}h，离线时长：{3}h", "# Run: {0}h, Alarm: {1}h, Idle: {2}h, Offline: {3}h", "# 稼働時間：{0}h、アラーム時間：{1}h、待機時間：{2}h、オフライン時間：{3}h", "# Execução: {0}h, Alarme: {1}h, Ocioso: {2}h, Offline: {3}h" },
        ["Csv_TargetCycle"] = new[] { "目标产能(件/小时)", "Target Output (pcs/h)", "目標能力(個/時)", "Capacidade alvo (peças/h)" },
        ["Csv_Time"] = new[] { "时间", "Time", "時刻", "Hora" },
        ["Csv_Value"] = new[] { "值", "Value", "値", "Valor" },
        ["DefectTop"] = new[] { "缺陷帕累托（TOP8）", "Defect Pareto (Top 8)", "不良パレート（TOP8）", "Pareto de defeitos (Top 8)" },
        ["Defect_Appearance"] = new[] { "外观", "Appearance", "外観", "Aparência" },
        ["Defect_Dimension"] = new[] { "尺寸", "Dimension", "寸法", "Dimensão" },
        ["Defect_Function"] = new[] { "功能", "Function", "機能", "Função" },
        ["Defect_Other"] = new[] { "其他", "Other", "その他", "Outro" },
        ["Defect_Packaging"] = new[] { "包装", "Packaging", "包装", "Embalagem" },
        ["Dv_AddressConfig"] = new[] { "地址配置", "Address Config", "アドレス設定", "Configuração de endereços" },
        ["Dv_AlarmConfig"] = new[] { "报警配置", "Alarm Config", "警報設定", "Configuração de alarmes" },
        ["Dv_AlarmCount"] = new[] { "报警 {0} 条", "{0} alarms", "警報 {0} 件", "{0} alarmes" },
        ["Dv_Category"] = new[] { "类别", "Category", "カテゴリ", "Categoria" },
        ["Dv_CountAlarmConfig"] = new[] { "计数器报警配置", "Counter Alarm Config", "カウント警報設定", "Configuração de alarmes de contador" },
        ["Dv_CountAlarmCount"] = new[] { "计数器报警 {0} 条", "{0} counter alarms", "カウント警報 {0} 件", "{0} alarmes de contador" },
        ["Dv_DefectConfig"] = new[] { "缺陷配置", "Defect Config", "欠陥設定", "Configuração de defeitos" },
        ["Dv_DefectCount"] = new[] { "缺陷 {0} 条", "{0} defects", "欠陥 {0} 件", "{0} defeitos" },
        ["Dv_Description"] = new[] { "描述", "Description", "説明", "Descrição" },
        ["Dv_Detail"] = new[] { "{0} 配置详情", "{0} Config Details", "{0} 設定詳細", "Detalhes da configuração de {0}" },
        ["Dv_DeviceId"] = new[] { "设备 ID", "Device ID", "デバイス ID", "ID do dispositivo" },
        ["Dv_LoadFailed"] = new[] { "设备配置加载失败", "Failed to load device configs", "デバイス設定の読み込みに失敗", "Falha ao carregar configurações de dispositivos" },
        ["Dv_LoadFailedHint"] = new[] { "请确认采集服务正常后重试", "Ensure the collection service is running and retry", "収集サービスの稼働を確認して再試行してください", "Confirme que o serviço de coleta está normal e tente novamente" },
        ["Dv_Loading"] = new[] { "正在加载设备配置", "Loading device configs", "デバイス設定を読み込み中", "Carregando configurações de dispositivos" },
        ["Dv_MachineType"] = new[] { "机型", "Machine Type", "機種", "Tipo de máquina" },
        ["Dv_Name"] = new[] { "名称", "Name", "名称", "Nome" },
        ["Dv_NgCountAddr"] = new[] { "NG 计数地址", "NG Count Address", "NG カウントアドレス", "Endereço de contagem NG" },
        ["Dv_NoDevices"] = new[] { "暂无设备配置", "No device configs", "デバイス設定なし", "Sem configurações de dispositivo" },
        ["Dv_None"] = new[] { "无配置", "None", "設定なし", "Sem configuração" },
        ["Dv_OkCountAddr"] = new[] { "OK 计数地址", "OK Count Address", "OK カウントアドレス", "Endereço de contagem OK" },
        ["Dv_PlcAddr"] = new[] { "PLC 地址", "PLC Address", "PLC アドレス", "Endereço PLC" },
        ["Dv_ReadOnly"] = new[] { "只读视图 · 写操作请使用 WPF 端", "Read-only · use WPF for edits", "読み取り専用 · 編集は WPF を使用", "Somente leitura · use o WPF para edições" },
        ["Dv_RecipeAddr"] = new[] { "配方地址", "Recipe Address", "レシピアドレス", "Endereço da receita" },
        ["Dv_ResetAddr"] = new[] { "产量复位地址", "Reset Address", "リセットアドレス", "Endereço de reset de produção" },
        ["Dv_Retry"] = new[] { "重试", "Retry", "再試行", "Tentar novamente" },
        ["Dv_Severity"] = new[] { "严重度", "Severity", "重大度", "Severidade" },
        ["Dv_StatusAddr"] = new[] { "状态字地址", "Status Word Address", "状態語アドレス", "Endereço da palavra de status" },
        ["Dv_Threshold"] = new[] { "阈值", "Threshold", "閾値", "Limiar" },
        ["Dv_Title"] = new[] { "设备管理（只读）", "Devices (Read-only)", "デバイス管理（読み取り専用）", "Dispositivos (somente leitura)" },
        ["Fresh_Live"] = new[] { "实时", "Live", "リアルタイム", "Em tempo real" },
        ["Fresh_Mins"] = new[] { "{0} 分钟前", "{0} min ago", "{0} 分前", "Há {0} min" },
        ["Fresh_None"] = new[] { "未收到", "Not received", "未受信", "Não recebido" },
        ["Fresh_Secs"] = new[] { "{0} 秒前", "{0}s ago", "{0} 秒前", "Há {0}s" },
        ["Home_Tip_ActualCycle"] = new[] { "实际周期（秒/件）= 3600 ÷ 当前速度。当前速度为 0 时显示 —。\\n当前速度 {0:N0} 件/h → {1}\\n与目标对比：{2}", "Actual cycle (s/pc) = 3600 ÷ current speed. Shows — when speed is 0.\\nCurrent speed {0:N0} pcs/h → {1}\\nVs target: {2}", "実サイクル（秒/個）= 3600 ÷ 現在速度。速度 0 のときは —。\\n現在速度 {0:N0} 個/h → {1}\\n目標との差：{2}", "Ciclo real (s/pç) = 3600 ÷ velocidade atual. Mostra — se a velocidade for 0.\\nVelocidade {0:N0} pçs/h → {1}\\nVs alvo: {2}" },
        ["Home_Tip_AlarmTime"] = new[] { "报警时长：设备处于「报警」状态的累计时间。占比分母含离线。\\n当前：{0}（{1:P0}）", "Alarm time: accumulated time in Alarm. Share includes offline in the denominator.\\nNow: {0} ({1:P0})", "警報時間：警報状態の累計。比率の分母にオフラインを含む。\\n現在：{0}（{1:P0}）", "Tempo em alarme: acumulado em Alarm. A parcela inclui offline no denominador.\\nAgora: {0} ({1:P0})" },
        ["Home_Tip_Availability"] = new[] { "可用率 = 运行时长 ÷ (运行+报警)。待机与离线不计入分母。\\n当前：{0} = {1}", "Availability = running time ÷ (running + alarm). Standby and offline are excluded from the denominator.\\nNow: {0} = {1}", "可動率 = 稼働時間 ÷ (稼働+警報)。待機とオフラインは分母に含めない。\\n現在：{0} = {1}", "Disponibilidade = tempo em execução ÷ (execução + alarme). Espera e offline ficam de fora do denominador.\\nAgora: {0} = {1}" },
        ["Home_Tip_Clock"] = new[] { "本机当前墙钟时间，格式 月-日 时:分:秒，主页可见时每秒刷新。\\n当前：{0}", "Local wall-clock time as MM-dd HH:mm:ss, refreshed every second while Home is visible.\\nNow: {0}", "ローカル壁時計。形式 月-日 時:分:秒。ホーム表示中は毎秒更新。\\n現在：{0}", "Relógio local no formato MM-dd HH:mm:ss, atualizado a cada segundo na Home.\\nAgora: {0}" },
        ["Home_Tip_CurrentShift"] = new[] { "本班次会话累计 OK / NG。箭头对比上一班次同期口径。\\nOK {0}   NG {1}", "Current-shift session OK / NG. Arrows compare with the previous shift.\\nOK {0}   NG {1}", "当シフトのセッション累計 OK / NG。矢印は前シフトとの差。\\nOK {0}   NG {1}", "OK / NG acumulados do turno atual. Setas comparam com o turno anterior.\\nOK {0}   NG {1}" },
        ["Home_Tip_LastShift"] = new[] { "上一完整班次的产量汇总。\\n{0}\\nOK {1:N0}   NG {2:N0}", "Previous complete shift output summary.\\n{0}\\nOK {1:N0}   NG {2:N0}", "直前の完了シフトの生産集計。\\n{0}\\nOK {1:N0}   NG {2:N0}", "Resumo do turno completo anterior.\\n{0}\\nOK {1:N0}   NG {2:N0}" },
        ["Home_Tip_NgRate"] = new[] { "不良率 = NG ÷ (OK+NG)，越低越好。无产量时为 0。\\n当前：{0:N0} / {1:N0} = {2}", "NG rate = NG ÷ (OK+NG); lower is better. 0 when there is no output.\\nNow: {0:N0} / {1:N0} = {2}", "不良率 = NG ÷ (OK+NG)。低いほど良い。生産なしは 0。\\n現在：{0:N0} / {1:N0} = {2}", "Taxa de NG = NG ÷ (OK+NG); quanto menor, melhor. 0 sem produção.\\nAgora: {0:N0} / {1:N0} = {2}" },
        ["Home_Tip_Oee"] = new[] { "OEE = 可用率 × 性能率 × 合格率。\\n当前：{0} = {1}\\n着色：≥85% 绿 / ≥60% 黄 / <60% 红。", "OEE = Availability × Performance × Quality.\\nNow: {0} = {1}\\nColors: ≥85% green / ≥60% yellow / <60% red.", "OEE = 可動率 × 性能率 × 良品率。\\n現在：{0} = {1}\\n色：≥85% 緑 / ≥60% 黄 / <60% 赤。", "OEE = Disponibilidade × Desempenho × Qualidade.\\nAgora: {0} = {1}\\nCores: ≥85% verde / ≥60% amarelo / <60% vermelho." },
        ["Home_Tip_OfflineTime"] = new[] { "离线时长：通讯中断、采集停止或状态字离线的累计时间。计入展示占比，不计入 OEE 可用率分母。\\n当前：{0}（{1:P0}）", "Offline time: accumulated time from comms loss, acquisition stop, or PLC offline. Included in display share, excluded from OEE availability denominator.\\nNow: {0} ({1:P0})", "オフライン時間：通信途絶・収集停止・状態語オフラインの累計。表示比率には含むが、OEE 可動率の分母には含めない。\\n現在：{0}（{1:P0}）", "Tempo offline: perda de comunicação, coleta parada ou PLC offline. Entra na parcela de exibição, não no denominador da disponibilidade do OEE.\\nAgora: {0} ({1:P0})" },
        ["Home_Tip_PausedTime"] = new[] { "待机时长：设备处于「待机/暂停」状态的累计时间。占比分母含离线。\\n当前：{0}（{1:P0}）", "Standby time: accumulated time in Paused/Standby. Share includes offline in the denominator.\\nNow: {0} ({1:P0})", "待機時間：一時停止/待機状態の累計。比率の分母にオフラインを含む。\\n現在：{0}（{1:P0}）", "Tempo em espera: acumulado em Paused/Standby. A parcela inclui offline no denominador.\\nAgora: {0} ({1:P0})" },
        ["Home_Tip_Performance"] = new[] { "性能率 = 实际总产量(OK+NG) ÷ (目标产能 × 运行小时)。\\n当前：{0} = {1}", "Performance = actual output (OK+NG) ÷ (target capacity × running hours).\\nNow: {0} = {1}", "性能率 = 実績総生産(OK+NG) ÷ (目標能力 × 稼働時間)。\\n現在：{0} = {1}", "Desempenho = produção real (OK+NG) ÷ (capacidade alvo × horas em execução).\\nAgora: {0} = {1}" },
        ["Home_Tip_Quality"] = new[] { "合格率 = OK ÷ (OK+NG)。良品率达标线 95%：达到为绿，否则为红。\\n当前：{0} = {1}", "Quality = OK ÷ (OK+NG). Target is 95%: green if met, otherwise red.\\nNow: {0} = {1}", "良品率 = OK ÷ (OK+NG)。目標 95%：達成で緑、未達で赤。\\n現在：{0} = {1}", "Qualidade = OK ÷ (OK+NG). Meta 95%: verde se atingida, senão vermelho.\\nAgora: {0} = {1}" },
        ["Home_Tip_QualityGap"] = new[] { "相对良品率目标 95% 的差距。正数=超出目标，负数=尚未达标。\\n当前合格率 {0}，差距 {1}", "Gap versus the 95% quality target. Positive = above target, negative = still short.\\nQuality now {0}, gap {1}", "良品率目標 95% との差。正=目標超過、負=未達。\\n現在の良品率 {0}、差 {1}", "Diferença em relação à meta de 95%. Positivo = acima, negativo = ainda abaixo.\\nQualidade agora {0}, diferença {1}" },
        ["Home_Tip_QualityTrend"] = new[] { "折线为本班次会话累计良率：各时点 OK ÷ (OK+NG)。红虚线为 95% 达标线。数据来自班次产量快照，并接上当前实时值。", "The line is cumulative shift quality: OK ÷ (OK+NG) at each sample. The dashed red line is the 95% target. Points come from shift production snapshots plus the live value.", "折れ線は当シフト累計良品率：各時点の OK ÷ (OK+NG)。赤破線は 95% 目標。シフト生産スナップショットに現在値を接続。", "A linha é a qualidade acumulada do turno: OK ÷ (OK+NG) em cada amostra. A linha vermelha tracejada é a meta de 95%. Pontos vêm dos snapshots do turno mais o valor ao vivo." },
        ["Home_Tip_RealtimeSpeed"] = new[] { "当前速度（件/小时）= (OK产量 + NG产量) ÷ 运行时长（小时）。\\n运行时长只在设备运行时累计；报警/待机期间产量与时长都不变，故速度保持。运行不足 5 秒显示为 0，避免启动瞬间失真。\\n当前：({0:N0}+{1:N0}) ÷ {2} = {3} 件/h", "Current speed (pcs/h) = (OK + NG) ÷ running hours.\\nRunTime accumulates only while Running; during alarm/standby both output and time stay still so speed holds. Below 5s running time the speed is 0 to avoid startup spikes.\\nNow: ({0:N0}+{1:N0}) ÷ {2} = {3} pcs/h", "現在速度（個/時）= (OK + NG) ÷ 稼働時間（時間）。\\n稼働時間は運転中のみ累計。警報/待機中は生産も時間も増えないため速度は維持。稼働 5 秒未満は 0（起動直後の歪み防止）。\\n現在：({0:N0}+{1:N0}) ÷ {2} = {3} 個/h", "Velocidade atual (pçs/h) = (OK + NG) ÷ horas em execução.\\nO tempo só acumula em Running; em alarme/espera a velocidade permanece. Abaixo de 5s a velocidade é 0.\\nAgora: ({0:N0}+{1:N0}) ÷ {2} = {3} pçs/h" },
        ["Home_Tip_RunTime"] = new[] { "运行时长：设备处于「运行」状态的累计时间。占比分母 = 运行+报警+待机+离线。\\n当前：{0}（{1:P0}）", "Running time: accumulated time in Running. Share denominator = run+alarm+standby+offline.\\nNow: {0} ({1:P0})", "稼働時間：運転状態の累計。比率の分母 = 運転+警報+待機+オフライン。\\n現在：{0}（{1:P0}）", "Tempo em execução: acumulado em Running. Denominador = execução+alarme+espera+offline.\\nAgora: {0} ({1:P0})" },
        ["Home_Tip_Shift"] = new[] { "当前班次名称与时间窗。百分比为班次已用时长 / 班次总时长。\\n{0}\\n{1}", "Current shift name and window. Percentage is elapsed / total shift length.\\n{0}\\n{1}", "現在のシフト名と時間帯。パーセントは経過 / シフト全長。\\n{0}\\n{1}", "Turno atual e janela. A porcentagem é decorrido / duração total do turno.\\n{0}\\n{1}" },
        ["Home_Tip_SpeedAchievement"] = new[] { "速度达成率 = 当前速度 ÷ 目标产能，结果限制在 0～100%。\\n当前速度 = (OK+NG) ÷ 运行小时；仅运行状态累计时长，报警/待机时速度保持不变；运行不足 5 秒时速度为 0。\\n当前：{0:N0} 件/h ÷ {1:N0} 件/h = {2:P0}\\n着色：≥90% 绿 / ≥70% 黄 / <70% 红。这不是工单完成率。", "Speed achievement = current speed ÷ target capacity, clamped to 0–100%.\\nCurrent speed = (OK+NG) ÷ running hours; RunTime accumulates only while Running and stays unchanged during alarm/standby; speed is 0 if RunTime < 5s.\\nNow: {0:N0} pcs/h ÷ {1:N0} pcs/h = {2:P0}\\nColors: ≥90% green / ≥70% yellow / <70% red. This is not work-order completion.", "速度達成率 = 現在速度 ÷ 目標能力（0～100% に制限）。\\n現在速度 = (OK+NG) ÷ 稼働時間（時間）；稼働状態のみ累計し、警報/待機中は変わりません。稼働が 5 秒未満なら 0。\\n現在：{0:N0} 個/h ÷ {1:N0} 個/h = {2:P0}\\n色：≥90% 緑 / ≥70% 黄 / <70% 赤。工単完成率ではありません。", "Taxa de realização = velocidade atual ÷ capacidade alvo, limitada a 0–100%.\\nVelocidade = (OK+NG) ÷ horas em execução; o tempo só acumula em Running e não muda em alarme/espera; 0 se RunTime < 5s.\\nAgora: {0:N0} pçs/h ÷ {1:N0} pçs/h = {2:P0}\\nCores: ≥90% verde / ≥70% amarelo / <70% vermelho. Não é a conclusão da ordem." },
        ["Home_Tip_TargetCycle"] = new[] { "目标周期（秒/件）= 3600 ÷ 设备目标产能（件/小时），来自设备配置。\\n当前目标产能 {0:N0} 件/h → {1}", "Target cycle (s/pc) = 3600 ÷ device target capacity (pcs/h), from device setup.\\nTarget capacity {0:N0} pcs/h → {1}", "目標サイクル（秒/個）= 3600 ÷ デバイス目標能力（個/時）。デバイス設定値。\\n目標能力 {0:N0} 個/h → {1}", "Ciclo alvo (s/pç) = 3600 ÷ capacidade alvo do dispositivo (pçs/h), da configuração.\\nCapacidade {0:N0} pçs/h → {1}" },
        ["Home_Tip_TotalOutput"] = new[] { "总产量 = OK + NG（会话累计，含不良品）。\\n当前：OK {0:N0} + NG {1:N0} = {2:N0} 件", "Total output = OK + NG (session cumulative, includes rejects).\\nNow: OK {0:N0} + NG {1:N0} = {2:N0} pcs", "総生産 = OK + NG（セッション累計、不良含む）。\\n現在：OK {0:N0} + NG {1:N0} = {2:N0} 個", "Produção total = OK + NG (acumulado da sessão, inclui rejeitos).\\nAgora: OK {0:N0} + NG {1:N0} = {2:N0} pçs" },
        ["Home_Tip_WorkOrderNg"] = new[] { "工单不良 = 工单时间窗口内的 NG 产量（非会话累计）。\\n当前：{0:N0} 件", "Work-order NG = reject count in the order time window (not session total).\\nNow: {0:N0} pcs", "工単不良 = 工単時間窓の NG 数（セッション累計ではない）。\\n現在：{0:N0} 個", "NG da ordem = rejeitos na janela da ordem (não o total da sessão).\\nAgora: {0:N0} pçs" },
        ["Home_Tip_WorkOrderOk"] = new[] { "工单已生产 = 工单时间窗口内的 OK 产量（非会话累计、不含 NG）。\\n当前：{0} 件", "Work-order produced = OK output in the order time window (not session total, excludes NG).\\nNow: {0} pcs", "工単生産済 = 工単時間窓の OK 数（セッション累計ではなく、NG を含まない）。\\n現在：{0} 個", "Produzido na ordem = OK na janela da ordem (não o total da sessão; exclui NG).\\nAgora: {0} pçs" },
        ["Home_Tip_WorkOrderProgress"] = new[] { "工单完成率 = 工单内 OK 产量 ÷ 计划产量，超额时封顶 100%。\\n口径为工单时间窗口内的合格产量（与工单管理页一致），不是会话累计，也不是速度达成率。\\n当前：{0:N0} / {1:N0} 件 = {2}", "Work-order completion = OK output in the order window ÷ planned quantity, capped at 100%.\\nUses OK count in the work-order time window (same as the Work Order page), not session totals and not speed achievement.\\nNow: {0:N0} / {1:N0} pcs = {2}", "工単完成率 = 工単内 OK 生産量 ÷ 計画数量（100% 上限）。\\n工単時間窓の合格数（作業指示ページと同じ）。セッション累計でも速度達成率でもありません。\\n現在：{0:N0} / {1:N0} 個 = {2}", "Conclusão da ordem = OK na janela da ordem ÷ quantidade planejada, limitado a 100%.\\nUsa OK da janela da ordem (igual à página de Ordens), não o total da sessão nem a realização de velocidade.\\nAgora: {0:N0} / {1:N0} pçs = {2}" },
        ["Home_Tip_WorkOrderQuality"] = new[] { "工单良率 = 工单内 OK ÷ (OK+NG)。无产量时显示 —。达标线 95%。\\n当前：{0:N0} / {1:N0} = {2}\\n与合格率卡片的会话累计良率口径不同。", "Work-order quality = OK ÷ (OK+NG) in the order window. Shows — when there is no output. Target is 95%.\\nNow: {0:N0} / {1:N0} = {2}\\nThis is not the session quality on the Quality card.", "工単良品率 = 工単内 OK ÷ (OK+NG)。生産なしは —。目標 95%。\\n現在：{0:N0} / {1:N0} = {2}\\n品質カードのセッション累計良品率とは口径が異なります。", "Qualidade da ordem = OK ÷ (OK+NG) na janela da ordem. Mostra — sem produção. Meta 95%.\\nAgora: {0:N0} / {1:N0} = {2}\\nNão é a qualidade acumulada da sessão no cartão de Qualidade." },
        ["Home_Tip_WorkOrderTarget"] = new[] { "工单设置数量 = 该工单的计划产量（目标件数）。\\n当前：{0:N0} 件", "Work-order target = planned quantity for this order.\\nNow: {0:N0} pcs", "工単設定数量 = この工単の計画生産数。\\n現在：{0:N0} 個", "Quantidade da ordem = quantidade planejada desta ordem.\\nAgora: {0:N0} pçs" },
        ["Home_WorkOrderNg"] = new[] { "工单不良", "Order NG", "工単不良", "NG da ordem" },
        ["Home_WorkOrderQuality"] = new[] { "工单良率", "Order Quality", "工単良品率", "Qualidade da ordem" },
        ["Hp_DefectCumulative"] = new[] { "累计 {0:P0}", "Cumul. {0:P0}", "累積 {0:P0}", "Acum. {0:P0}" },
        ["Hp_DefectEmptyUnconfigured"] = new[] { "未配置缺陷项", "No defect items configured", "不良項目未設定", "Nenhum item de defeito configurado" },
        ["Hp_DefectEmptyUnconfiguredHint"] = new[] { "请在设备管理中配置缺陷名称和 PLC 地址", "Configure defect names and PLC addresses in Device Manager", "設備管理で不良名と PLC アドレスを設定してください", "Configure nomes e endereços PLC em Gerenciador de dispositivos" },
        ["Hp_DefectEmptyZero"] = new[] { "当前无不良计数", "No defect counts right now", "現在の不良カウントなし", "Sem contagem de defeitos agora" },
        ["Hp_DefectEmptyZeroHint"] = new[] { "已配置的缺陷地址当前均为 0", "Configured defect registers are all 0", "設定済み不良アドレスはすべて 0", "Os endereços de defeito configurados estão em 0" },
        ["Hp_DefectOthers"] = new[] { "其他（{0} 项）", "Others ({0})", "その他（{0} 件）", "Outros ({0})" },
        ["Hp_DefectShareNg"] = new[] { "占 NG {0:P0}", "{0:P0} of NG", "NG比 {0:P0}", "{0:P0} do NG" },
        ["Hp_DefectSubtitle"] = new[] { "当前设备 · 本班次新增", "Current device · shift increment", "現在の設備 · 当シフト増分", "Dispositivo atual · incremento do turno" },
        ["Hp_DefectSummary"] = new[] { "缺陷合计 {0:N0}", "Defect total {0:N0}", "不良合計 {0:N0}", "Total de defeitos {0:N0}" },
        ["Hp_DefectTooltip"] = new[] { "{0} · {1} · {2}", "{0} · {1} · {2}", "{0} · {1} · {2}", "{0} · {1} · {2}" },
        ["Hp_DefectTooltipNoAddr"] = new[] { "{0} · {1}", "{0} · {1}", "{0} · {1}", "{0} · {1}" },
        ["Hq_AlarmChart"] = new[] { "报警频次排行（Top 20）", "Alarm Frequency (Top 20)", "アラーム頻度（Top 20）", "Frequência de alarmes (Top 20)" },
        ["Hq_AlarmEvents"] = new[] { "报警事件", "Alarm Events", "アラームイベント", "Eventos de alarme" },
        ["Hq_AlarmHintBody"] = new[] { "选择设备与时间范围后点击“查询”，可查看触发/恢复/待恢复统计、频次排行与事件明细", "Select a device and time range, then click Search for trigger/recover/pending stats, frequency and events", "デバイスと時間範囲を選択して「検索」をクリックすると、発生/復旧/未復旧の統計・頻度・イベントを確認できます", "Selecione o dispositivo e o período e clique em Consultar para ver estatísticas de disparo/recuperação/pendentes, frequência e eventos" },
        ["Hq_AlarmHintTitle"] = new[] { "报警历史查询", "Alarm History Query", "警報履歴照会", "Consulta de histórico de alarmes" },
        ["Hq_AlarmId"] = new[] { "报警 ID", "Alarm ID", "アラーム ID", "ID do alarme" },
        ["Hq_AlarmName"] = new[] { "报警名称", "Alarm Name", "アラーム名", "Nome do alarme" },
        ["Hq_AlarmPending"] = new[] { "待恢复", "Pending", "未復旧", "Pendente" },
        ["Hq_AlarmPlc"] = new[] { "PLC 地址", "PLC Address", "PLC アドレス", "Endereço PLC" },
        ["Hq_AlarmRecovered"] = new[] { "恢复", "Recovered", "復旧", "Recuperado" },
        ["Hq_AlarmTriggered"] = new[] { "触发", "Triggered", "発生", "Disparado" },
        ["Hq_AlarmType"] = new[] { "事件类型", "Event Type", "イベント種別", "Tipo de evento" },
        ["Hq_AllAlarms"] = new[] { "全部报警", "All Alarms", "全アラーム", "Todos os alarmes" },
        ["Hq_AllDevices"] = new[] { "全部设备", "All Devices", "全デバイス", "Todos os dispositivos" },
        ["Hq_AllShifts"] = new[] { "全部班次", "All Shifts", "全シフト", "Todos os turnos" },
        ["Hq_Analyzing"] = new[] { "正在分析数据…", "Analyzing data…", "データを分析中…", "Analisando dados…" },
        ["Hq_ChartNg"] = new[] { "NG 产量", "NG Output", "NG 生産量", "Produção NG" },
        ["Hq_ChartOk"] = new[] { "OK 产量", "OK Output", "OK 生産量", "Produção OK" },
        ["Hq_ChartTitle"] = new[] { "产量趋势（15 分钟分桶）", "Production Trend (15-min buckets)", "生産トレンド（15分バケット）", "Tendência de produção (baldes de 15 min)" },
        ["Hq_CurrState"] = new[] { "当前状态", "Current State", "現在の状態", "Estado atual" },
        ["Hq_Custom"] = new[] { "自定义", "Custom", "カスタム", "Personalizado" },
        ["Hq_Device"] = new[] { "设备", "Device", "デバイス", "Dispositivo" },
        ["Hq_DeviceId"] = new[] { "设备 ID", "Device ID", "デバイス ID", "ID do dispositivo" },
        ["Hq_DeviceName"] = new[] { "设备名称", "Device Name", "デバイス名", "Nome do dispositivo" },
        ["Hq_EventTime"] = new[] { "事件时间", "Event Time", "イベント時刻", "Hora do evento" },
        ["Hq_Export"] = new[] { "导出 CSV", "Export CSV", "CSV エクスポート", "Exportar CSV" },
        ["Hq_ExportEmpty"] = new[] { "当前页无数据可导出", "Nothing to export on this page", "このページにエクスポート対象がありません", "Nada para exportar nesta página" },
        ["Hq_From"] = new[] { "开始", "From", "開始", "De" },
        ["Hq_HintBody"] = new[] { "选择设备与时间范围后点击“查询”，可查看 KPI、15 分钟产量趋势与明细", "Select a device and time range, then click Search for KPI, 15-min trend and details", "デバイスと時間範囲を選択して「検索」をクリックすると、KPI・15分トレンド・明細を確認できます", "Selecione o dispositivo e o período e clique em Consultar para ver KPIs, tendência de 15 min e detalhes" },
        ["Hq_HintTitle"] = new[] { "产量历史查询", "Production History Query", "生産履歴照会", "Consulta de histórico de produção" },
        ["Hq_InsAlarmChain"] = new[] { "连锁触发模式 {0} 出现 {1} 次", "Chain trigger pattern {0} x{1}", "連鎖発生パターン {0} が {1} 回", "Padrão de disparo em cadeia {0} x{1}" },
        ["Hq_InsAlarmPending"] = new[] { "待恢复报警：{0}", "Pending alarms: {0}", "未復旧警報：{0}", "Alarmes pendentes de recuperação: {0}" },
        ["Hq_InsAlarmPendingItem"] = new[] { "{0}（{1}，自 {2}）", "{0} ({1}, since {2})", "{0}（{1}、{2} から）", "{0} ({1}, desde {2})" },
        ["Hq_InsAlarmRatio"] = new[] { "报警占比 {0:P0}，超过阈值 {1:P0}", "Alarm ratio {0:P0}, above threshold {1:P0}", "警報割合 {0:P0}、閾値 {1:P0} 超", "Proporção de alarmes {0:P0}, acima do limiar {1:P0}" },
        ["Hq_InsAlarmTop"] = new[] { "{0}（{1} 次，占 {2:P0}）", "{0} ({1} times, {2:P0})", "{0}（{1} 回、{2:P0}）", "{0} ({1} vezes, {2:P0})" },
        ["Hq_InsAlarmTop3"] = new[] { "报警频次 TOP3：{0}", "Alarm frequency TOP3: {0}", "警報頻度 TOP3：{0}", "Frequência de alarmes TOP3: {0}" },
        ["Hq_InsLongestAlarm"] = new[] { "最长连续报警 {0} 分钟（{1} ~ {2}）", "Longest alarm {0} min ({1} ~ {2})", "最長連続警報 {0} 分（{1} ~ {2}）", "Maior alarme contínuo de {0} min ({1} ~ {2})" },
        ["Hq_InsLongestAlarmLong"] = new[] { "⚠ 单次报警超 30 分钟：最长 {0} 分钟（{1} ~ {2}）", "⚠ Alarm over 30 min: longest {0} min ({1} ~ {2})", "⚠ 30分超の警報：最長 {0} 分（{1} ~ {2}）", "⚠ Alarme acima de 30 min: o maior durou {0} min ({1} ~ {2})" },
        ["Hq_InsLongestPause"] = new[] { "最长连续待机 {0} 分钟（{1} ~ {2}）", "Longest pause {0} min ({1} ~ {2})", "最長連続待機 {0} 分（{1} ~ {2}）", "Maior espera contínua de {0} min ({1} ~ {2})" },
        ["Hq_InsLongestRun"] = new[] { "最长连续运行 {0} 分钟（{1} ~ {2}）", "Longest run {0} min ({1} ~ {2})", "最長連続稼働 {0} 分（{1} ~ {2}）", "Maior execução contínua de {0} min ({1} ~ {2})" },
        ["Hq_InsOeeBalance"] = new[] { "合格率 {0:P0} × 性能率 {1:P0} × 可用率 {2:P0} = OEE {3:P0}", "Quality {0:P0} × Performance {1:P0} × Availability {2:P0} = OEE {3:P0}", "良品率 {0:P0} × 性能率 {1:P0} × 稼働率 {2:P0} = OEE {3:P0}", "Qualidade {0:P0} × Desempenho {1:P0} × Disponibilidade {2:P0} = OEE {3:P0}" },
        ["Hq_InsOeeGap"] = new[] { "{0}（{1:P0}）领先 {2}（{3:P0}）", "{0} ({1:P0}) leads {2} ({3:P0})", "{0}（{1:P0}）が {2}（{3:P0}）より高い", "{0} ({1:P0}) à frente de {2} ({3:P0})" },
        ["Hq_InsOeeWeak"] = new[] { "{0} 偏低（{1:P0}），是 OEE 短板", "{0} is low ({1:P0}), the OEE bottleneck", "{0} が低い（{1:P0}）、OEE の足を引っ張る要因", "{0} baixo ({1:P0}), o gargalo do OEE" },
        ["Hq_InsPauseRatio"] = new[] { "待机占比 {0:P0}，超过阈值 {1:P0}", "Paused ratio {0:P0}, above threshold {1:P0}", "待機割合 {0:P0}、閾値 {1:P0} 超", "Proporção em espera {0:P0}, acima do limiar {1:P0}" },
        ["Hq_InsShiftDrag"] = new[] { "主要拖累：{0}（{1:P0} vs 最佳 {2:P0}）", "Main drag: {0} ({1:P0} vs best {2:P0})", "主な原因：{0}（{1:P0} vs 最高 {2:P0}）", "Maior arrasto: {0} ({1:P0} vs melhor {2:P0})" },
        ["Hq_InsShiftWorst"] = new[] { "班次 {0}（{1}）OEE {2:P0} 最低，与最佳班次差距 {3:P0}", "Shift {0} ({1}) has lowest OEE {2:P0}, {3:P0} behind the best", "シフト {0}（{1}）の OEE {2:P0} が最低、最高シフトより {3:P0} 低い", "Turno {0} ({1}) com o menor OEE {2:P0}, {3:P0} atrás do melhor" },
        ["Hq_InsightDrop"] = new[] { "检测到 {0} 次突降，最严重 {1} 下降 {2:P0}（{3} → {4} 件）", "{0} sudden drop(s), worst {1} -{2:P0} ({3} → {4} pcs)", "急落 {0} 回、最悪 {1} -{2:P0}（{3} → {4} 個）", "{0} queda(s) súbita(s), a pior {1} -{2:P0} ({3} → {4} pçs)" },
        ["Hq_InsightPeakHigh"] = new[] { "峰值 {0} 件（{1}），高于均值 {2:P0}", "Peak {0} ({1}), {2:P0} above avg", "ピーク {0} 個（{1}）、平均より {2:P0} 高い", "Pico {0} ({1}), {2:P0} acima da média" },
        ["Hq_InsightPeakLow"] = new[] { "峰值 {0} 件（{1}），低于均值 {2:P0}", "Peak {0} ({1}), {2:P0} below avg", "ピーク {0} 個（{1}）、平均より {2:P0} 低い", "Pico {0} ({1}), {2:P0} abaixo da média" },
        ["Hq_InsightSteady"] = new[] { "平均 {0} 件/桶，峰值 {1} 件（{2}），产量平稳", "Avg {0}/bucket, peak {1} ({2}), steady output", "平均 {0} 個/バケット、ピーク {1} 個（{2}）、安定", "Média {0}/balde, pico {1} ({2}), produção estável" },
        ["Hq_Last30d"] = new[] { "近 30 天", "Last 30 Days", "直近30日", "Últimos 30 dias" },
        ["Hq_Last7d"] = new[] { "近 7 天", "Last 7 Days", "直近7日", "Últimos 7 dias" },
        ["Hq_Loading"] = new[] { "查询中", "Querying", "照会中", "Consultando" },
        ["Hq_NeedDevice"] = new[] { "请先选择设备（该 Tab 按单设备查询）", "Select a device first (this tab queries one device)", "先にデバイスを選択してください（このタブは単一デバイス照会）", "Selecione primeiro um dispositivo (esta aba consulta um por vez)" },
        ["Hq_NextPage"] = new[] { "下一页", "Next", "次へ", "Próxima" },
        ["Hq_NgCol"] = new[] { "NG", "NG", "NG", "NG" },
        ["Hq_NoData"] = new[] { "暂无数据", "No Data", "データなし", "Sem dados" },
        ["Hq_NoDataHint"] = new[] { "请调整时间范围或设备筛选后重试", "Adjust the time range or device filter and retry", "時間範囲またはデバイス条件を変更して再試行してください", "Ajuste o período ou o filtro de dispositivo e tente novamente" },
        ["Hq_OeeDetails"] = new[] { "班次 OEE 明细", "Shift OEE Details", "シフト OEE 明細", "Detalhes de OEE por turno" },
        ["Hq_OeeHintBody"] = new[] { "选择设备与时间范围后点击“查询”，可查看四率、班次 OEE 趋势与明细", "Select a device and time range, then click Search for the four rates, shift OEE trend and details", "デバイスと時間範囲を選択して「検索」をクリックすると、四率・シフト OEE トレンド・明細を確認できます", "Selecione o dispositivo e o período e clique em Consultar para ver as quatro taxas, tendência de OEE por turno e detalhes" },
        ["Hq_OeeHintTitle"] = new[] { "OEE 历史查询", "OEE History Query", "OEE 履歴照会", "Consulta de histórico de OEE" },
        ["Hq_OeeOverview"] = new[] { "OEE 综合概览", "Overall OEE", "OEE 総合", "Visão geral do OEE" },
        ["Hq_OeeTrend"] = new[] { "班次 OEE 趋势", "Shift OEE Trend", "シフト OEE トレンド", "Tendência de OEE por turno" },
        ["Hq_OkCol"] = new[] { "OK", "OK", "OK", "OK" },
        ["Hq_PageInfo"] = new[] { "第 {0} / {1} 页 · 共 {2} 条", "Page {0} / {1} · {2} rows", "{0} / {1} ページ · 全 {2} 件", "Página {0} / {1} · {2} linhas" },
        ["Hq_PrevPage"] = new[] { "上一页", "Prev", "前へ", "Anterior" },
        ["Hq_PrevState"] = new[] { "前一状态", "Previous State", "前状態", "Estado anterior" },
        ["Hq_QualityRate"] = new[] { "合格率", "Quality Rate", "良品率", "Taxa de qualidade" },
        ["Hq_QueryFailed"] = new[] { "查询失败，请确认采集服务正常后重试", "Query failed. Ensure the collection service is running", "照会に失敗しました。収集サービスの稼働を確認してください", "Falha na consulta. Confirme que o serviço de coleta está em execução" },
        ["Hq_QuickRange"] = new[] { "快捷时间", "Quick Range", "クイック範囲", "Tempo rápido" },
        ["Hq_Reset"] = new[] { "重置", "Reset", "リセット", "Redefinir" },
        ["Hq_Search"] = new[] { "查询", "Search", "検索", "Consultar" },
        ["Hq_Shift"] = new[] { "班次", "Shift", "シフト", "Turno" },
        ["Hq_ShiftChange"] = new[] { "班次切换", "Shift Change", "シフト切替", "Troca de turno" },
        ["Hq_ShiftTime"] = new[] { "开始时间", "Start Time", "開始時刻", "Hora de início" },
        ["Hq_StateUnknown"] = new[] { "未知", "Unknown", "不明", "Desconhecido" },
        ["Hq_StatusAlarm"] = new[] { "报警时长", "Alarm Time", "アラーム時間", "Tempo de alarmes" },
        ["Hq_StatusDaily"] = new[] { "每日状态时长（小时）", "Daily State Hours", "日別状態時間（時間）", "Horas de estado por dia" },
        ["Hq_StatusGantt"] = new[] { "状态甘特图", "Status Gantt", "状態ガントチャート", "Gantt de estados" },
        ["Hq_StatusHintBody"] = new[] { "选择设备与时间范围后点击“查询”，可查看状态时长占比、每日分布、甘特图与转换明细", "Select a device and time range, then click Search for state durations, daily distribution, gantt and transitions", "デバイスと時間範囲を選択して「検索」をクリックすると、状態時間・日別分布・ガントチャート・遷移明細を確認できます", "Selecione o dispositivo e o período e clique em Consultar para ver durações por estado, distribuição diária, gantt e transições" },
        ["Hq_StatusHintTitle"] = new[] { "状态历史查询", "Status History Query", "状態履歴照会", "Consulta de histórico de estados" },
        ["Hq_StatusOffline"] = new[] { "离线时长", "Offline Time", "オフライン時間", "Tempo offline" },
        ["Hq_StatusPause"] = new[] { "待机时长", "Paused Time", "待機時間", "Tempo em espera" },
        ["Hq_StatusPie"] = new[] { "状态时长占比", "State Duration Share", "状態時間割合", "Proporção de duração por estado" },
        ["Hq_StatusRun"] = new[] { "运行时长", "Run Time", "稼働時間", "Tempo de execução" },
        ["Hq_StatusTransitions"] = new[] { "状态转换记录", "Status Transitions", "状態遷移記録", "Transições de estado" },
        ["Hq_StatusWord"] = new[] { "状态字", "Status Word", "状態語", "Palavra de status" },
        ["Hq_ThisMonth"] = new[] { "本月", "This Month", "今月", "Este mês" },
        ["Hq_ThisWeek"] = new[] { "本周", "This Week", "今週", "Esta semana" },
        ["Hq_Time"] = new[] { "时间", "Time", "時間", "Hora" },
        ["Hq_To"] = new[] { "结束", "To", "終了", "Até" },
        ["Hq_Today"] = new[] { "今天", "Today", "今日", "Hoje" },
        ["Hq_TotalNg"] = new[] { "总 NG", "Total NG", "NG 合計", "Total NG" },
        ["Hq_TotalOk"] = new[] { "总 OK", "Total OK", "OK 合計", "Total OK" },
        ["Hq_Truncated"] = new[] { "数据量超过 10 万条上限，KPI/图表基于已取部分数据（建议缩小时间范围）", "Over 100k rows; KPI/chart based on fetched subset (narrow the time range)", "10万件超のため、KPI・グラフは取得済みデータに基づきます（時間範囲を絞ってください）", "Mais de 100 mil linhas; KPI/gráfico com base na parte obtida (reduza o período)" },
        ["Hq_ValidationRange"] = new[] { "请检查开始/结束时间（格式 yyyy-MM-ddTHH:mm，且开始不得晚于结束）", "Check from/to (format yyyy-MM-ddTHH:mm, from must not be later than to)", "開始/終了時刻を確認してください（形式 yyyy-MM-ddTHH:mm、開始は終了より後にできません）", "Verifique início/fim (formato yyyy-MM-ddTHH:mm, início não pode ser posterior ao fim)" },
        ["Hq_Yesterday"] = new[] { "昨天", "Yesterday", "昨日", "Ontem" },
        ["K326"] = new[] { "工单目标", "Order Target", "工単目標", "Meta da ordem" },
        ["K327"] = new[] { "工单完成", "Order Completion", "工単完了", "Conclusão da ordem" },
        ["K328"] = new[] { "当前班次良率", "Current Shift Quality", "当シフト良品率", "Qualidade do turno atual" },
        ["LastShift"] = new[] { "上一班次", "Last Shift", "前シフト", "Turno anterior" },
        ["LastShiftLine"] = new[] { "{0}：OK {1}（{2}）· NG {3}（{4}）", "{0}: OK {1} ({2}) · NG {3} ({4})", "{0}：OK {1}（{2}）· NG {3}（{4}）", "{0}: OK {1} ({2}) · NG {3} ({4})" },
        ["Lbl_Achievement"] = new[] { "达成率", "Achievement", "達成率", "Realização" },
        ["Lbl_ActualCycle"] = new[] { "实际周期", "Actual cycle time", "実サイクルタイム", "Tempo de ciclo real" },
        ["Lbl_Availability"] = new[] { "可用率", "Availability", "稼働率", "Disponibilidade" },
        ["Lbl_ConnStatus"] = new[] { "连接状态", "Connection", "接続状態", "Conexão" },
        ["Lbl_DataFresh"] = new[] { "数据更新", "Data Freshness", "データ更新", "Atualização dos dados" },
        ["Lbl_DevTotal"] = new[] { "设备总数", "Total Devices", "デバイス総数", "Total de dispositivos" },
        ["Lbl_Elapsed"] = new[] { "已运行", "Elapsed", "稼働時間", "Decorrido" },
        ["Lbl_Ng"] = new[] { "NG 不良", "NG Defect", "NG 不良", "NG defeito" },
        ["Lbl_NgRate"] = new[] { "不良率", "NG Rate", "不良率", "Taxa de NG" },
        ["Lbl_Ok"] = new[] { "OK 良品", "OK Good", "OK 良品", "OK bom" },
        ["Lbl_Performance"] = new[] { "性能率", "Performance", "性能率", "Desempenho" },
        ["Lbl_Quality"] = new[] { "合格率", "Quality", "良品率", "Qualidade" },
        ["Lbl_RealTimeSpeed"] = new[] { "实时速度（件/小时）", "Real-time Speed (pcs/h)", "リアルタイム速度（個/時）", "Velocidade em tempo real (pçs/h)" },
        ["Lbl_Remaining"] = new[] { "剩余", "Remaining", "残り", "Restante" },
        ["Lbl_SnapSeq"] = new[] { "快照序号", "Snapshot Seq", "スナップショット番号", "Seq. do snapshot" },
        ["Lbl_SvcAddr"] = new[] { "服务地址", "Service Address", "サービスアドレス", "Endereço do serviço" },
        ["Lbl_SvcVersion"] = new[] { "服务版本", "Service Version", "サービスバージョン", "Versão do serviço" },
        ["Lbl_TargetCapacity"] = new[] { "目标产能", "Target Output", "目標能力", "Capacidade alvo" },
        ["Lbl_TargetCycle"] = new[] { "目标周期", "Target cycle time", "目標サイクルタイム", "Tempo de ciclo alvo" },
        ["Lbl_TotalOutput"] = new[] { "总产量", "Total Output", "総生産量", "Produção total" },
        ["Ln_AvailabilityHint"] = new[] { "只扣报警时间，不含待机和离线", "Counts alarm time only; excludes standby and offline", "アラーム時間のみ控除（待機・オフライン含まず）", "Desconta apenas alarme; exclui espera e offline" },
        ["Ln_CurrentShift"] = new[] { "当前班次", "Current Shift", "現在のシフト", "Turno atual" },
        ["Ln_Cycle"] = new[] { "平均周期（实际/目标）", "Avg cycle time (actual/target)", "平均サイクルタイム（実績/目標）", "Tempo de ciclo médio (real/alvo)" },
        ["Ln_DevCount"] = new[] { "共 {0} 台设备", "{0} devices", "デバイス {0} 台", "{0} dispositivos" },
        ["Ln_Downtime"] = new[] { "停机", "Downtime", "停止", "Parada" },
        ["Ln_EmptyFilter"] = new[] { "没有匹配的设备", "No matching devices", "一致するデバイスがありません", "Nenhum dispositivo correspondente" },
        ["Ln_FilterAll"] = new[] { "全部状态", "All Statuses", "全状態", "Todos os status" },
        ["Ln_NoDevices"] = new[] { "暂无设备", "No devices", "デバイスなし", "Sem dispositivos" },
        ["Ln_NoDevicesHint"] = new[] { "请确认采集服务与仿真器已启动", "Ensure the collection service and simulator are running", "収集サービスとシミュレーターの起動を確認してください", "Confirme que o serviço de coleta e o simulador estão em execução" },
        ["Ln_Search"] = new[] { "搜索设备", "Search devices", "デバイス検索", "Pesquisar dispositivos" },
        ["Ln_ShiftProgress"] = new[] { "班次进度", "Shift Progress", "シフト進捗", "Progresso do turno" },
        ["Ln_SortName"] = new[] { "按名称", "By Name", "名前順", "Por nome" },
        ["Ln_SortOee"] = new[] { "按 OEE", "By OEE", "OEE 順", "Por OEE" },
        ["Ln_SortOutput"] = new[] { "按产量", "By Output", "生産順", "Por produção" },
        ["Ln_Title"] = new[] { "产线总览", "Production Line Overview", "生産ライン概要", "Visão geral da linha de produção" },
        ["Ln_WeightedOee"] = new[] { "加权 OEE", "Weighted OEE", "加重 OEE", "OEE ponderado" },
        ["Meta_PlanWo"] = new[] { "计划 {0} 件", "Planned {0} pcs", "計画 {0} 個", "Planejado {0} pçs" },
        ["Meta_QualityRate"] = new[] { "合格率 {0} · 不良率 {1}", "Quality {0} · NG rate {1}", "良品率 {0} · 不良率 {1}", "Qualidade {0} · Taxa de NG {1}" },
        ["Meta_ShiftAuto"] = new[] { "按班次配置自动计算", "Auto-calculated from shift config", "シフト設定から自動計算", "Calculado automaticamente pela configuração de turnos" },
        ["Meta_StatusWord"] = new[] { "状态字 0x{0} · 目标 {1} 件/h", "Status word 0x{0} · Target {1} pcs/h", "状態語 0x{0} · 目標 {1} 個/h", "Palavra de status 0x{0} · Meta {1} pçs/h" },
        ["Meta_TrendCurrent"] = new[] { "当前 {0} 件/h · 采样 0.5s", "Current {0} pcs/h · Sampling 0.5s", "現在 {0} 個/h · サンプリング 0.5秒", "Atual {0} pçs/h · Amostragem 0,5s" },
        ["Mo_AcqRunning"] = new[] { "采集中", "Acquiring", "収集中", "Coletando" },
        ["Mo_AcqStatus"] = new[] { "采集状态", "Acquisition", "収集状態", "Coleta" },
        ["Mo_AcqStopped"] = new[] { "已停止", "Stopped", "停止中", "Parada" },
        ["Mo_AvgCycleMs"] = new[] { "平均循环耗时", "Avg Cycle", "平均サイクル", "Ciclo médio" },
        ["Mo_CompletedCycles"] = new[] { "完成循环", "Completed Cycles", "完了サイクル", "Ciclos concluídos" },
        ["Mo_ConsecutiveFail"] = new[] { "连续失败", "Consecutive Failures", "連続失敗", "Falhas consecutivas" },
        ["Mo_CycleHealth"] = new[] { "采集循环健康", "Acquisition Cycle Health", "収集サイクル健全性", "Saúde do ciclo de coleta" },
        ["Mo_DbSize"] = new[] { "数据库大小", "DB Size", "DB サイズ", "Tamanho do banco" },
        ["Mo_DeviceLive"] = new[] { "设备实时状态", "Live Device Status", "デバイスリアルタイム状態", "Status em tempo real dos dispositivos" },
        ["Mo_DevicesRead"] = new[] { "设备读取", "Devices Read", "デバイス読取", "Dispositivos lidos" },
        ["Mo_Disconnects"] = new[] { "断连次数", "Disconnects", "切断回数", "Desconexões" },
        ["Mo_EstimatedOps"] = new[] { "估算读操作", "Est. Read Ops", "推定読取回数", "Leituras estimadas" },
        ["Mo_FailedCycles"] = new[] { "失败循环", "Failed Cycles", "失敗サイクル", "Ciclos com falha" },
        ["Mo_FlushFailures"] = new[] { "落库失败", "Flush Failures", "書込失敗", "Falhas de gravação" },
        ["Mo_HistoryHealth"] = new[] { "历史落库健康", "History Persistence", "履歴保存健全性", "Saúde de persistência do histórico" },
        ["Mo_LastCycleMs"] = new[] { "最近循环耗时", "Last Cycle", "直近サイクル", "Último ciclo" },
        ["Mo_LastFailureAt"] = new[] { "上次失败", "Last Failure", "最終失敗", "Última falha" },
        ["Mo_LastFlushAt"] = new[] { "上次落库", "Last Flush", "最終書込", "Última gravação" },
        ["Mo_LastSuccessAt"] = new[] { "上次成功", "Last Success", "最終成功", "Último sucesso" },
        ["Mo_Live3s"] = new[] { "3s 刷新", "Refresh 3s", "3秒更新", "Atualização 3s" },
        ["Mo_MaxCycleMs"] = new[] { "最大循环耗时", "Max Cycle", "最大サイクル", "Ciclo máximo" },
        ["Mo_PendingHistory"] = new[] { "历史积压", "History Backlog", "履歴滞留", "Acúmulo de histórico pendente" },
        ["Mo_RecoveryFile"] = new[] { "恢复文件", "Recovery File", "リカバリファイル", "Arquivo de recuperação" },
        ["Mo_Refresh10s"] = new[] { "10s 刷新", "Refresh 10s", "10秒更新", "Atualização 10s" },
        ["Mo_SuccessRate"] = new[] { "采集成功率", "Cycle Success Rate", "サイクル成功率", "Taxa de sucesso do ciclo" },
        ["Mo_TimingBreakdown"] = new[] { "读取耗时分解（ms）", "Read Timing Breakdown (ms)", "読取時間内訳（ms）", "Decomposição do tempo de leitura (ms)" },
        ["Mo_TmAlarm"] = new[] { "报警", "Alarm", "警報", "Alarme" },
        ["Mo_TmBatchPlan"] = new[] { "批计划", "Batch Plan", "バッチ計画", "Plano de lote" },
        ["Mo_TmCountAlarm"] = new[] { "计数器报警", "Counter Alarm", "カウント警報", "Alarme de contador" },
        ["Mo_TmDefect"] = new[] { "缺陷", "Defect", "欠陥", "Defeito" },
        ["Mo_TmDword"] = new[] { "字读取", "DWord Read", "ワード読取", "Leitura de palavra" },
        ["Mo_TmHistory"] = new[] { "历史写入", "History Write", "履歴書込", "Gravação de histórico" },
        ["Msg_EmptyHint"] = new[] { "确认 PlcSimulator 与 Kanban.Collector 已启动，且 CollectorHubUrl 端口一致", "Ensure PlcSimulator and Kanban.Collector are running and the CollectorHubUrl port matches", "PlcSimulator と Kanban.Collector が起動し、CollectorHubUrl のポートが一致していることを確認してください", "Confirme que PlcSimulator e Kanban.Collector estão em execução e que a porta de CollectorHubUrl é a mesma" },
        ["Msg_NoDevSelected"] = new[] { "未选择设备", "No device selected", "デバイス未選択", "Nenhum dispositivo selecionado" },
        ["Msg_NoDeviceData"] = new[] { "暂无设备数据", "No device data", "デバイスデータなし", "Sem dados de dispositivos" },
        ["Msg_SelectHint"] = new[] { "从右上角选择要查看的设备", "Select a device from the top right", "右上から表示するデバイスを選択してください", "Selecione o dispositivo no canto superior direito" },
        ["Msg_WaitingConn"] = new[] { "等待连接采集服务…", "Waiting for the collection service…", "収集サービスへの接続待ち…", "Aguardando o serviço de coleta…" },
        ["Nav_AlarmCenter"] = new[] { "报警中心", "Alarm Center", "警報センター", "Central de alarmes" },
        ["Nav_Audit"] = new[] { "审计", "Audit", "監査", "Auditoria" },
        ["Nav_Dashboard"] = new[] { "看板", "Dashboard", "ダッシュボード", "Painel" },
        ["Nav_Devices"] = new[] { "设备", "Devices", "デバイス", "Dispositivos" },
        ["Nav_History"] = new[] { "历史查询", "History Query", "履歴照会", "Consulta de histórico" },
        ["Nav_Line"] = new[] { "产线预览", "Production Line", "生産ライン", "Linha de produção" },
        ["Nav_Monitoring"] = new[] { "运行监控", "Runtime Monitoring", "稼働監視", "Monitoramento de execução" },
        ["Nav_Recipes"] = new[] { "配方", "Recipes", "レシピ", "Receitas" },
        ["Nav_Review"] = new[] { "生产复盘", "Production Review", "生産レビュー", "Revisão de produção" },
        ["Nav_Settings"] = new[] { "设置", "Settings", "設定", "Configurações" },
        ["Nav_WorkOrders"] = new[] { "工单", "Work Orders", "工単", "Ordens" },
        ["NoDefectData"] = new[] { "暂无缺陷数据", "No defect data", "欠陥データなし", "Sem dados de defeitos" },
        ["Pl_Cancel"] = new[] { "取消", "Cancel", "キャンセル", "Cancelar" },
        ["Pl_ResetAll"] = new[] { "全部清零", "Reset All", "一括クリア", "Zerar tudo" },
        ["Pl_ResetAllConfirm"] = new[] { "确定清零全部 {0} 台设备的 OEE 吗？此操作不可撤销。", "Reset OEE for all {0} devices? This cannot be undone.", "全 {0} 台のデバイスの OEE をクリアしますか？この操作は取消できません。", "Zerar o OEE de todos os {0} dispositivos? Esta operação não pode ser desfeita." },
        ["Pl_ResetAllFail"] = new[] { "全部设备 OEE 清零失败：{0}", "Reset OEE for all devices failed: {0}", "全デバイス OEE クリア失敗：{0}", "Falha ao zerar o OEE de todos os dispositivos: {0}" },
        ["Pl_ResetAllHint"] = new[] { "全部设备 OEE 清零", "Reset OEE for All Devices", "全デバイスの OEE クリア", "Zerar OEE de todos os dispositivos" },
        ["Pl_ResetAllOk"] = new[] { "已触发全部设备 OEE 清零（{0}/{1} 台）", "OEE reset triggered for all devices ({0}/{1})", "全デバイスの OEE クリアを実行しました（{0}/{1} 台）", "Zeramento de OEE acionado para todos os dispositivos ({0}/{1})" },
        ["Rc_ItemCount"] = new[] { "{0} 个参数", "{0} params", "{0} パラメータ", "{0} parâmetros" },
        ["Rc_None"] = new[] { "暂无配方", "No recipes", "レシピなし", "Sem receitas" },
        ["Rc_Title"] = new[] { "配方管理（只读）", "Recipes (Read-only)", "レシピ管理（読み取り専用）", "Receitas (somente leitura)" },
        ["Recipe"] = new[] { "配方", "Recipe", "レシピ", "Receita" },
        ["RecipeInfo"] = new[] { "配方 {0}：{1}", "Recipe {0}: {1}", "レシピ {0}：{1}", "Receita {0}: {1}" },
        ["Rv_AlarmCol"] = new[] { "报警", "Alarms", "警報", "Alarmes" },
        ["Rv_AlarmCount"] = new[] { "报警次数", "Alarm Count", "警報回数", "Nº de alarmes" },
        ["Rv_AlarmCountConclusion"] = new[] { "当前范围共触发 {0:N0} 次报警，请结合 Top 5 报警确认主要停机来源", "{0:N0} alarms triggered; check Top 5 alarms for downtime sources", "この期間に警報 {0:N0} 回発生、Top5 警報で停止要因を確認してください", "{0:N0} disparos de alarme no período; consulte o Top 5 de alarmes para as causas de parada" },
        ["Rv_AlarmRank"] = new[] { "报警排行（Top 5）", "Alarm Ranking (Top 5)", "警報ランキング（Top 5）", "Ranking de alarmes (Top 5)" },
        ["Rv_BaselineOee"] = new[] { "上一周期 OEE", "Previous OEE", "前周期の OEE", "OEE do período anterior" },
        ["Rv_BaselineOutput"] = new[] { "上一周期产量", "Previous Output", "前周期の生産", "Produção do período anterior" },
        ["Rv_BaselineQuality"] = new[] { "上一周期良品率", "Previous Quality", "前周期の良品率", "Qualidade do período anterior" },
        ["Rv_BestShiftConclusion"] = new[] { "{0}产量最高，共 {1:N0} 件，良品率 {2:P1}", "{0} has the highest output ({1:N0} pcs), quality {2:P1}", "{0} の生産が最多（{1:N0} 個）、良品率 {2:P1}", "{0} tem a maior produção ({1:N0} pçs), qualidade {2:P1}" },
        ["Rv_Comparison"] = new[] { "周期对比", "Period Comparison", "期間比較", "Comparação de períodos" },
        ["Rv_ComparisonHint"] = new[] { "当前设备与上一周期的变化", "Changes vs the previous period", "前周期との変化", "Mudanças em relação ao período anterior" },
        ["Rv_Conclusions"] = new[] { "复盘结论", "Conclusions", "レビュー結論", "Conclusões da revisão" },
        ["Rv_ConclusionsHint"] = new[] { "基于当前生产、设备与质量数据生成", "Generated from production, device and quality data", "生産・設備・品質データから生成", "Gerado a partir dos dados de produção, dispositivo e qualidade" },
        ["Rv_CurrentOutput"] = new[] { "当前总产量", "Current Output", "今回の総生産", "Produção total atual" },
        ["Rv_CurrentShift"] = new[] { "当前班次", "Current Shift", "現在のシフト", "Turno atual" },
        ["Rv_DowntimeConclusion"] = new[] { "最长停机为 {0:F1} 小时，设备：{1}，报警：{2}", "Longest downtime {0:F1} h, device: {1}, alarm: {2}", "最長停止 {0:F1} 時間、設備：{1}、警報：{2}", "Maior parada de {0:F1} h, dispositivo: {1}, alarme: {2}" },
        ["Rv_Health"] = new[] { "设备健康评分", "Device Health", "デバイス健康スコア", "Saúde do dispositivo" },
        ["Rv_HealthAlarmSpike"] = new[] { "报警突增：当前 {0} 次，上一周期 {1} 次", "Alarm spike: {0} now vs {1} last period", "警報急増：今回 {0} 回、前周期 {1} 回", "Surto de alarmes: {0} agora vs {1} no período anterior" },
        ["Rv_HealthDefectSpike"] = new[] { "缺陷率突增：当前 {0} 个，上一周期 {1} 个", "Defect spike: {0} now vs {1} last period", "欠陥急増：今回 {0} 個、前周期 {1} 個", "Surto de defeitos: {0} agora vs {1} no período anterior" },
        ["Rv_HealthLowOutput"] = new[] { "产能偏低：实际 {0:F1} 件/小时，低于目标 {1:F0} 件/小时的 80%", "Low output: actual {0:F1} pcs/h, target {1:F0} pcs/h, below 80%", "能力低下：実績 {0:F1} 個/時、目標 {1:F0} 個/時の 80%", "Produção baixa: real {0:F1} pcs/h, meta {1:F0} pcs/h, abaixo de 80%" },
        ["Rv_HealthNoOutput"] = new[] { "运行无产量：{0}-{1} 持续 {2:F0} min", "Running with no output: {0}-{1} for {2:F0} min", "稼働中に生産なし：{0}-{1} で {2:F0} 分", "Em execução sem produção: {0}-{1} por {2:F0} min" },
        ["Rv_HintBody"] = new[] { "选择设备与时间范围后点击“查询”，生成健康评分、复盘结论与周期对比", "Select a device and time range, then click Search for health score, conclusions and period comparison", "デバイスと時間範囲を選択して「検索」をクリックすると、健康スコア・結論・期間比較を確認できます", "Selecione o dispositivo e o período e clique em Consultar para gerar pontuação de saúde, conclusões e comparação de períodos" },
        ["Rv_HintTitle"] = new[] { "生产复盘分析", "Production Review", "生産レビュー分析", "Revisão de produção" },
        ["Rv_LongestDowntime"] = new[] { "最长停机", "Longest Downtime", "最長停止", "Maior parada" },
        ["Rv_Met"] = new[] { "达到", "Met", "達成", "Atingiu" },
        ["Rv_NoConclusion"] = new[] { "当前时间范围没有足够的产量或报警数据生成复盘结论", "Not enough output or alarm data in this range to generate conclusions", "この期間には結論を生成するのに十分な生産・警報データがありません", "Dados de produção ou alarmes insuficientes no período para gerar conclusões" },
        ["Rv_NoIssues"] = new[] { "未发现健康问题", "No health issues found", "健康上の問題なし", "Nenhum problema de saúde encontrado" },
        ["Rv_NotMet"] = new[] { "低于", "Below", "未達", "Abaixo" },
        ["Rv_OeeConclusion"] = new[] { "OEE 为 {0:P1}，{1} {2:P0} 目标", "OEE is {0:P1}, {1} the {2:P0} target", "OEE {0:P1}、目標 {2:P0} を{1}", "O OEE é {0:P1}, {1} a meta de {2:P0}" },
        ["Rv_OutputAchievement"] = new[] { "产能达成", "Output achievement", "能力達成", "Realização da capacidade" },
        ["Rv_PeakHour"] = new[] { "峰值时段", "Peak Hour", "ピーク時間帯", "Hora de pico" },
        ["Rv_PeakValleyOk"] = new[] { "OK {0} 件 · 占 {1:P0}", "OK {0} pcs · {1:P0} share", "OK {0} 個 · {1:P0} の割合", "OK {0} pçs · {1:P0} do total" },
        ["Rv_Product"] = new[] { "产品 / 批次", "Product / Batch", "製品 / ロット", "Produto / Lote" },
        ["Rv_QualityConclusion"] = new[] { "良品率为 {0:P1}，{1} {2:P0} 目标", "Quality is {0:P1}, {1} the {2:P0} target", "良品率 {0:P1}、目標 {2:P0} を{1}", "A taxa de qualidade é {0:P1}, {1} a meta de {2:P0}" },
        ["Rv_Recipe"] = new[] { "当前配方", "Current Recipe", "現在のレシピ", "Receita atual" },
        ["Rv_RecipeHint"] = new[] { "配方值来自当前设备配置", "Recipe value from device config", "レシピ値はデバイス設定から", "Valor da receita vem da configuração do dispositivo" },
        ["Rv_ShiftDetails"] = new[] { "班次明细", "Shift Details", "シフト明細", "Detalhes por turno" },
        ["Rv_Timeline"] = new[] { "设备状态时间线", "Status Timeline", "状態タイムライン", "Linha do tempo de estados" },
        ["Rv_TimelineHint"] = new[] { "运行、报警、待机与未知区间；悬浮查看该段产量与报警", "Run, alarm, pause and unknown segments; hover for output and alarms", "稼働・警報・待機・不明区間。ホバーで生産と警報を確認", "Segmentos de execução, alarme, espera e desconhecido; passe o mouse para ver produção e alarmes" },
        ["Rv_TopDefectConclusion"] = new[] { "主要缺陷为 {0}（{1}），当前累计 {2:N0} 件，占当前缺陷 Top10 的 {3:F1}%", "Top defect: {0} ({1}), {2:N0} pcs, {3:F1}%", "主要欠陥は {0}（{1}）、累計 {2:N0} 個、Top10 の {3:F1}%", "Defeito principal: {0} ({1}), {2:N0} pcs, {3:F1}%" },
        ["Rv_Trend"] = new[] { "产量趋势", "Output Trend", "生産トレンド", "Tendência de produção" },
        ["Rv_ValleyHour"] = new[] { "谷值时段", "Valley Hour", "ボトム時間帯", "Hora de vale" },
        ["Rv_WorkOrder"] = new[] { "当前工单", "Current Work Order", "現在の工単", "Ordem de produção atual" },
        ["Severity_Critical"] = new[] { "严重", "Critical", "重大", "Crítico" },
        ["Severity_Major"] = new[] { "一般", "Major", "一般", "Maior" },
        ["Severity_Minor"] = new[] { "轻微", "Minor", "軽微", "Leve" },
        ["St_Acquisition"] = new[] { "采集参数", "Acquisition", "収集パラメータ", "Parâmetros de coleta" },
        ["St_AddrZero"] = new[] { "地址从 0 开始", "Zero-based Addr", "0 起点アドレス", "Endereço a partir de 0" },
        ["St_BatchGapSlots"] = new[] { "批读最大间隙", "Batch Read Gap", "バッチ読取ギャップ", "Lacuna máx. de leitura em lote" },
        ["St_BatchInt32"] = new[] { "BatchInt32 上限", "BatchInt32 Limit", "BatchInt32 上限", "Limite de BatchInt32" },
        ["St_BatchMaxLen"] = new[] { "批读最大长度", "Batch Read Max", "バッチ読取最大長", "Máx. de leitura em lote" },
        ["St_DataFormat"] = new[] { "数据格式", "Data Format", "データ形式", "Formato de dados" },
        ["St_HistoryScans"] = new[] { "历史写入间隔（扫描次）", "History Write (scans)", "履歴書込間隔（スキャン）", "Gravação de histórico (varreduras)" },
        ["St_NoShifts"] = new[] { "未配置班次", "No shifts configured", "シフト未設定", "Turnos não configurados" },
        ["St_Plc"] = new[] { "PLC 连接", "PLC Connection", "PLC 接続", "Conexão PLC" },
        ["St_PlcBrand"] = new[] { "PLC 品牌", "PLC Brand", "PLC ブランド", "Marca do PLC" },
        ["St_PlcIp"] = new[] { "IP 地址", "IP Address", "IP アドレス", "Endereço IP" },
        ["St_PlcPort"] = new[] { "端口", "Port", "ポート", "Porta" },
        ["St_PlcTimeout"] = new[] { "超时", "Timeout", "タイムアウト", "Timeout" },
        ["St_PollingMs"] = new[] { "轮询间隔", "Polling Interval", "ポーリング間隔", "Intervalo de varredura" },
        ["St_RackSlot"] = new[] { "机架 / 槽位", "Rack / Slot", "ラック / スロット", "Rack / Slot" },
        ["St_ReadSplits"] = new[] { "读取分段", "Read Splits", "読取分割", "Divisões de leitura" },
        ["St_Shifts"] = new[] { "班次配置", "Shift Config", "シフト設定", "Configuração de turnos" },
        ["St_SiemensModel"] = new[] { "机型", "Model", "機種", "Modelo" },
        ["St_Title"] = new[] { "采集设置（只读）", "Settings (Read-only)", "収集設定（読み取り専用）", "Configurações de coleta (somente leitura)" },
        ["St_UnitId"] = new[] { "站号（UnitId）", "UnitId", "ユニット ID", "UnitId" },
        ["Status_Alarm"] = new[] { "报警", "Alarm", "アラーム", "Alarme" },
        ["Status_Idle"] = new[] { "空闲", "Idle", "アイドル", "Ocioso" },
        ["Status_Offline"] = new[] { "离线", "Offline", "オフライン", "Offline" },
        ["Status_Offline_AcquisitionStopped"] = new[] { "离线（采集停止）", "Offline (acquisition stopped)", "オフライン（収集停止）", "Offline (coleta parada)" },
        ["Status_Offline_CommsLost"] = new[] { "离线（通讯中断）", "Offline (comms lost)", "オフライン（通信切断）", "Offline (comunicação)" },
        ["Status_Offline_GapFilled"] = new[] { "离线（采集空窗）", "Offline (acquisition gap)", "オフライン（収集欠落）", "Offline (lacuna de coleta)" },
        ["Status_Offline_PlcReported"] = new[] { "离线（PLC）", "Offline (PLC)", "オフライン（PLC）", "Offline (PLC)" },
        ["Status_Paused"] = new[] { "待机", "Standby", "待機", "Em espera" },
        ["Status_Running"] = new[] { "运行", "Running", "稼働中", "Em execução" },
        ["Tab_Alarm"] = new[] { "报警", "Alarm", "警報", "Alarme" },
        ["Tab_Oee"] = new[] { "OEE", "OEE", "OEE", "OEE" },
        ["Tab_Production"] = new[] { "产量", "Production", "生産", "Produção" },
        ["Tab_Status"] = new[] { "状态", "Status", "状態", "Estado" },
        ["Unit_PerHour"] = new[] { "件/h", "pcs/h", "個/h", "peças/h" },
        ["Val_DynAddr"] = new[] { "动态派生 · :5129", "Auto-derived · :5129", "自動導出 · :5129", "Derivado automaticamente · :5129" },
        ["Val_No"] = new[] { "否", "No", "いいえ", "Não" },
        ["Val_NoAlarms"] = new[] { "当前无激活报警", "No active alarms", "アクティブ警報なし", "Nenhum alarme ativo" },
        ["Val_NoData"] = new[] { "无数据", "No Data", "データなし", "Sem dados" },
        ["Val_NoWorkOrder"] = new[] { "暂无工单", "No work orders", "作業指示なし", "Sem ordens de produção" },
        ["Val_WaitData"] = new[] { "等待数据积累…", "Waiting for data…", "データ蓄積待ち…", "Aguardando acumular dados…" },
        ["Val_Yes"] = new[] { "是", "Yes", "はい", "Sim" },
        ["Wo_Aborted"] = new[] { "已终止", "Aborted", "中止", "Abortada" },
        ["Wo_Completed"] = new[] { "已完成", "Completed", "完了", "Concluída" },
        ["Wo_DoneNg"] = new[] { "完成 NG", "Done NG", "完了 NG", "NG concluído" },
        ["Wo_DoneOk"] = new[] { "完成 OK", "Done OK", "完了 OK", "OK concluído" },
        ["Wo_List"] = new[] { "工单列表", "Work Order List", "工単リスト", "Lista de ordens de produção" },
        ["Wo_None"] = new[] { "暂无工单", "No work orders", "工単なし", "Sem ordens de produção" },
        ["Wo_OrderNo"] = new[] { "工单号", "Order No", "工単番号", "Nº do pedido" },
        ["Wo_Pending"] = new[] { "待开始", "Pending", "未開始", "Pendente" },
        ["Wo_PlanEnd"] = new[] { "计划结束", "Planned End", "計画終了", "Fim planejado" },
        ["Wo_PlanQty"] = new[] { "计划量", "Target Qty", "計画数", "Quantidade alvo" },
        ["Wo_PlanStart"] = new[] { "计划开始", "Planned Start", "計画開始", "Início planejado" },
        ["Wo_Product"] = new[] { "产品", "Product", "製品", "Produto" },
        ["Wo_Progress"] = new[] { "{0} / {1} 件", "{0} / {1} pcs", "{0} / {1} 個", "{0} / {1} pçs" },
        ["Wo_ProgressPending"] = new[] { "-- / {0} 件", "-- / {0} pcs", "-- / {0} 個", "-- / {0} pçs" },
        ["Wo_Running"] = new[] { "生产中", "In Production", "生産中", "Em produção" },
        ["Wo_Status"] = new[] { "状态", "Status", "状態", "Status" },
        ["Wo_Title"] = new[] { "工单管理（只读）", "Work Orders (Read-only)", "工単管理（読み取り専用）", "Ordens de produção (somente leitura)" },
    };
    private static readonly Dictionary<string, int> LanguageIndices = new(StringComparer.OrdinalIgnoreCase)
    {
        ["zh-CN"] = 0,
        ["en-US"] = 1,
        ["ja-JP"] = 2,
        ["pt-BR"] = 3,
    };
    private static readonly string[] LegacyLanguageCodes = ["zh-CN", "en-US", "ja-JP", "pt-BR"];
    private static Dictionary<string, string[]> s_values = Clone(BuiltinD);

    public static IReadOnlyList<string> LanguageCodes => LanguageIndices.Keys.ToArray();
    public const string DefaultLanguage = "zh-CN";
    public static string Current { get; set; } = DefaultLanguage;

    public static bool IsSupportedLanguage(string? language)
        => language is not null && LanguageIndices.ContainsKey(language);

    public static string NormalizeLanguage(string? language)
        => LanguageIndices.Keys.FirstOrDefault(code =>
            string.Equals(code, language, StringComparison.OrdinalIgnoreCase))
            ?? DefaultLanguage;

    /// <summary>把旧版屏端的语言序号转换为动态语言代码。</summary>
    public static string FromLegacyIndex(int index)
    {
        if (index < 0 || index >= LegacyLanguageCodes.Length)
            return DefaultLanguage;
        return IsSupportedLanguage(LegacyLanguageCodes[index])
            ? NormalizeLanguage(LegacyLanguageCodes[index])
            : DefaultLanguage;
    }

    /// <summary>合并 Collector 启动时读取的 WPF 文案覆盖；未知 Web Key 会被忽略。</summary>
    public static void ApplyOverrides(IEnumerable<LocalizationOverrideDto> overrides)
    {
        var values = Clone(BuiltinD);

        foreach (var item in overrides)
        {
            if (!string.Equals(item.Resource, "Wpf", StringComparison.Ordinal)
                || !LanguageIndices.TryGetValue(NormalizeLanguage(item.CultureName), out var languageIndex))
                continue;

            var key = item.Key.StartsWith("Web_", StringComparison.Ordinal)
                ? item.Key[4..]
                : item.Key;
            if (values.TryGetValue(key, out var languageValues)
                && BuiltinD.TryGetValue(key, out var builtinValues)
                && HasCompatibleFormat(builtinValues[languageIndex], item.Value))
                languageValues[languageIndex] = item.Value;
        }
        Interlocked.Exchange(ref s_values, values);
    }

    private static bool HasCompatibleFormat(string expected, string actual)
    {
        if (!TryGetPlaceholderSignature(expected, out var expectedSignature)
            || !TryGetPlaceholderSignature(actual, out var actualSignature)
            || !expectedSignature.OrderBy(pair => pair.Key)
                .SequenceEqual(actualSignature.OrderBy(pair => pair.Key)))
            return false;

        try
        {
            var maxIndex = actualSignature.Keys.DefaultIfEmpty(-1).Max();
            var arguments = Enumerable.Range(0, maxIndex + 1)
                .Select(_ => (object)new FormatProbe())
                .ToArray();
            _ = string.Format(CultureInfo.InvariantCulture, actual, arguments);
            return true;
        }
        catch (FormatException)
        {
            return false;
        }
        catch (ArgumentException)
        {
            return false;
        }
    }

    private static bool TryGetPlaceholderSignature(
        string value,
        out Dictionary<int, int> signature)
    {
        signature = new Dictionary<int, int>();
        var maxIndex = -1;
        for (var index = 0; index < value.Length;)
        {
            if (value[index] == '{')
            {
                if (index + 1 < value.Length && value[index + 1] == '{')
                {
                    index += 2;
                    continue;
                }

                index++;
                var start = index;
                while (index < value.Length && char.IsDigit(value[index])) index++;
                if (start == index || !int.TryParse(value[start..index], out var argumentIndex))
                    return false;
                maxIndex = Math.Max(maxIndex, argumentIndex);

                if (index < value.Length && value[index] == ',')
                {
                    index++;
                    while (index < value.Length && char.IsWhiteSpace(value[index])) index++;
                    if (index < value.Length && value[index] == '-') index++;
                    start = index;
                    while (index < value.Length && char.IsDigit(value[index])) index++;
                    if (start == index) return false;
                    while (index < value.Length && char.IsWhiteSpace(value[index])) index++;
                }

                if (index < value.Length && value[index] == ':')
                {
                    index++;
                    while (index < value.Length && value[index] != '}')
                    {
                        if (value[index] == '{') return false;
                        index++;
                    }
                }

                if (index >= value.Length || value[index] != '}') return false;
                signature[argumentIndex] = signature.TryGetValue(argumentIndex, out var count)
                    ? count + 1
                    : 1;
                index++;
            }
            else if (value[index] == '}')
            {
                if (index + 1 < value.Length && value[index + 1] == '}')
                {
                    index += 2;
                    continue;
                }
                return false;
            }
            else
            {
                index++;
            }
        }
        return maxIndex < 0 || signature.Keys.All(argumentIndex => argumentIndex <= maxIndex);
    }

    private sealed class FormatProbe : IFormattable
    {
        public string ToString(string? format, IFormatProvider? formatProvider) => "x";
        public override string ToString() => "x";
    }

    private static Dictionary<string, string[]> Clone(Dictionary<string, string[]> source)
        => source.ToDictionary(pair => pair.Key, pair => pair.Value.ToArray());

    public static string T(string key, params object[] args)
    {
        var values = Volatile.Read(ref s_values);
        if (values.TryGetValue(key, out var languageValues))
        {
            var languageIndex = LanguageIndices.TryGetValue(Current, out var index) ? index : 0;
            var text = languageValues[languageIndex];
            if (args.Length == 0) return text;
            try
            {
                return string.Format(text, args);
            }
            catch (FormatException)
            {
                return text;
            }
        }
        return key;
    }
}
