using System.Globalization;
using Kanban.Contracts.Dtos;

namespace Kanban.Web;

/// <summary>屏端语言代码常量。新增语言由 Localization.csv 表头自动加入运行时目录。</summary>
public static class WebLanguage
{
    public const string zh_CN = "zh-CN";
    public const string en_US = "en-US";
    public const string ja_JP = "ja-JP";
    public const string pt_BR = "pt-BR";
}

/// <summary>
/// WASM 屏端多语言字典（语言代码由 Localization.csv 表头定义）。
/// WARNING: AUTO-GENERATED by ci/generate_localization.py. DO NOT EDIT MANUALLY.
/// All 394 keys are derived from Localization.csv Wpf rows.
/// </summary>
public static class L
{
    private static readonly Dictionary<string, string[]> BuiltinD = new()
    {
        ["Ac_ActiveCount"] = new[] { "当前活跃", "Active Alarms", "現在の警報", "Active Alarms" },
        ["Ac_ActiveTitle"] = new[] { "实时活跃报警", "Live Active Alarms", "リアルタイム警報", "Live Active Alarms" },
        ["Ac_AffectedDevices"] = new[] { "涉及设备", "Devices Affected", "影響デバイス", "Devices Affected" },
        ["Ac_AlarmName"] = new[] { "报警名称", "Alarm Name", "アラーム名", "Alarm Name" },
        ["Ac_Count"] = new[] { "次数", "Count", "回数", "Count" },
        ["Ac_Device"] = new[] { "设备", "Device", "デバイス", "Device" },
        ["Ac_Level"] = new[] { "级别", "Level", "レベル", "Level" },
        ["Ac_LevelHigh"] = new[] { "高", "High", "高", "High" },
        ["Ac_LevelLow"] = new[] { "低", "Low", "低", "Low" },
        ["Ac_LevelMedium"] = new[] { "中", "Medium", "中", "Medium" },
        ["Ac_Longest"] = new[] { "最长持续", "Longest Active", "最長継続", "Longest Active" },
        ["Ac_Range1h"] = new[] { "近 1 小时", "Last 1 Hour", "直近1時間", "Last 1 Hour" },
        ["Ac_Range24h"] = new[] { "近 24 小时", "Last 24 Hours", "直近24時間", "Last 24 Hours" },
        ["Ac_Range4h"] = new[] { "近 4 小时", "Last 4 Hours", "直近4時間", "Last 4 Hours" },
        ["Ac_Rank"] = new[] { "排名", "Rank", "順位", "Rank" },
        ["Ac_RecentTitle"] = new[] { "最近事件", "Recent Events", "最近のイベント", "Recent Events" },
        ["Ac_StatsTitle"] = new[] { "报警统计", "Alarm Statistics", "警報統計", "Alarm Statistics" },
        ["Ac_TodayRecover"] = new[] { "今日恢复", "Today Recovered", "今日の復旧", "Today Recovered" },
        ["Ac_TodayTrigger"] = new[] { "今日触发", "Today Triggered", "今日の発生", "Today Triggered" },
        ["Ac_TopTitle"] = new[] { "触发次数 Top 10", "Trigger Count Top 10", "トリガー回数 TOP 10", "Trigger Count Top 10" },
        ["Ac_TotalDuration"] = new[] { "累计时长", "Total Duration", "累計時間", "Total Duration" },
        ["Au_Action"] = new[] { "操作类型", "Action", "操作種別", "Action" },
        ["Au_AllResults"] = new[] { "全部结果", "All Results", "全結果", "All Results" },
        ["Au_Detail"] = new[] { "详情", "Detail", "詳細", "Detail" },
        ["Au_Failed"] = new[] { "失败", "Failed", "失敗", "Failed" },
        ["Au_List"] = new[] { "审计记录", "Audit Records", "監査記録", "Audit Records" },
        ["Au_None"] = new[] { "暂无审计记录", "No audit records", "監査記録なし", "No audit records" },
        ["Au_Operator"] = new[] { "操作人", "Operator", "操作者", "Operator" },
        ["Au_Result"] = new[] { "结果", "Result", "結果", "Result" },
        ["Au_Success"] = new[] { "成功", "Success", "成功", "Success" },
        ["Au_TargetId"] = new[] { "对象 ID", "Target ID", "対象 ID", "Target ID" },
        ["Au_TargetType"] = new[] { "对象类型", "Target Type", "対象種別", "Target Type" },
        ["Au_Title"] = new[] { "审计查询（只读）", "Audit Log (Read-only)", "監査ログ（読み取り専用）", "Audit Log (Read-only)" },
        ["Badge_Recent1Min"] = new[] { "近 1 分钟", "Last 1 min", "直近1分", "Last 1 min" },
        ["Card_Alarms"] = new[] { "实时故障", "Live Alarms", "リアルタイム故障", "Live Alarms" },
        ["Card_DevCount"] = new[] { "设备总数", "Total Devices", "デバイス総数", "Total Devices" },
        ["Card_DevStatus"] = new[] { "设备状态", "Device Status", "設備状態", "Device Status" },
        ["Card_Oee"] = new[] { "OEE 概览", "OEE Overview", "OEE 概要", "OEE Overview" },
        ["Card_Output"] = new[] { "产量明细", "Output Details", "生産明細", "Output Details" },
        ["Card_ProdStatus"] = new[] { "当前生产状态", "Current Production", "現在の生産状態", "Current Production" },
        ["Card_Shift"] = new[] { "班次进度", "Shift Progress", "シフト進捗", "Shift Progress" },
        ["Card_Source"] = new[] { "数据源", "Data Source", "データソース", "Data Source" },
        ["Card_Trend"] = new[] { "速度趋势", "Speed Trend", "速度トレンド", "Speed Trend" },
        ["Card_WorkOrder"] = new[] { "当前工单", "Current Work Order", "現在の工単", "Current Work Order" },
        ["ConnLost"] = new[] { "连接中断，正在重连…", "Connection lost, reconnecting…", "接続が切れました。再接続中…", "Connection lost, reconnecting…" },
        ["ConnStale"] = new[] { "数据停滞 {0}s，采集服务可能卡死", "Data stalled for {0}s; the collection service may be stuck", "データが {0}s 停滞しています。収集サービスが停止している可能性があります", "Data stalled for {0}s; the collection service may be stuck" },
        ["Conn_Connected"] = new[] { "已连接", "Connected", "接続済み", "Connected" },
        ["Conn_Disconnected"] = new[] { "未连接", "Disconnected", "未接続", "Disconnected" },
        ["Conn_Live"] = new[] { "实时", "Live", "リアルタイム", "Live" },
        ["Csv_AlarmId"] = new[] { "报警ID", "Alarm ID", "アラームID", "ID do alarme" },
        ["Csv_AlarmName"] = new[] { "报警名称", "Alarm Name", "アラーム名", "Nome do alarme" },
        ["Csv_AlarmSeconds"] = new[] { "报警时长(s)", "Alarm Time (s)", "アラーム時間(s)", "Tempo de alarme (s)" },
        ["Csv_CurrState"] = new[] { "当前状态", "Current State", "現在状態", "Estado atual" },
        ["Csv_CurrStateText"] = new[] { "当前状态文本", "Current State Text", "現在状態テキスト", "Texto do estado atual" },
        ["Csv_DeviceId"] = new[] { "设备ID", "Device ID", "設備ID", "ID do dispositivo" },
        ["Csv_DeviceName"] = new[] { "设备名称", "Device Name", "設備名", "Nome do dispositivo" },
        ["Csv_EventTime"] = new[] { "事件时间", "Event Time", "イベント時刻", "Hora do evento" },
        ["Csv_EventType"] = new[] { "事件类型", "Event Type", "イベント種別", "Tipo de evento" },
        ["Csv_EventTypeText"] = new[] { "事件类型文本", "Event Type Text", "イベント種別テキスト", "Texto do tipo de evento" },
        ["Csv_FileAlarm"] = new[] { "报警_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "alarms_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "alarms_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "alarms_{0:yyyyMMdd}_{1:yyyyMMdd}.csv" },
        ["Csv_FileProd"] = new[] { "产量_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "production_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "production_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "production_{0:yyyyMMdd}_{1:yyyyMMdd}.csv" },
        ["Csv_FileStatus"] = new[] { "状态时长_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "status_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "status_{0:yyyyMMdd}_{1:yyyyMMdd}.csv", "status_{0:yyyyMMdd}_{1:yyyyMMdd}.csv" },
        ["Csv_Metric"] = new[] { "指标", "Metric", "指標", "Métrica" },
        ["Csv_NgCount"] = new[] { "NG产量", "NG Output", "NG生産数", "Produção NG" },
        ["Csv_OkCount"] = new[] { "OK产量", "OK Output", "OK生産数", "Produção OK" },
        ["Csv_PlcAddress"] = new[] { "PLC地址", "PLC Address", "PLCアドレス", "Endereço PLC" },
        ["Csv_PrevState"] = new[] { "前一状态", "Previous State", "前回状態", "Estado anterior" },
        ["Csv_PrevStateText"] = new[] { "前一状态文本", "Previous State Text", "前回状態テキスト", "Texto do estado anterior" },
        ["Csv_RunSeconds"] = new[] { "运行时长(s)", "Run Time (s)", "稼働時間(s)", "Tempo de execução (s)" },
        ["Csv_Shift"] = new[] { "班次", "Shift", "シフト", "Turno" },
        ["Csv_StatusWord"] = new[] { "状态字", "Status Word", "ステータスワード", "Palavra de status" },
        ["Csv_SumAlarm"] = new[] { "# 触发：{0} 次，恢复：{1} 次，待恢复：{2} 条", "# Triggered: {0}, Recovered: {1}, Pending: {2}", "# 発報：{0} 回、復旧：{1} 回、未復旧：{2} 件", "# Disparados: {0}, Recuperados: {1}, Pendentes: {2}" },
        ["Csv_SumDevice"] = new[] { "# 设备：{0}", "# Device: {0}", "# 設備：{0}", "# Dispositivo: {0}" },
        ["Csv_SumProd"] = new[] { "# 总 OK：{0} 件，总 NG：{1} 件，良品率：{2}", "# Total OK: {0}, Total NG: {1}, Yield: {2}", "# OK合計：{0} 個、NG合計：{1} 個、良品率：{2}", "# Total OK: {0}, Total NG: {1}, Rendimento: {2}" },
        ["Csv_SumRange"] = new[] { "# 查询区间：{0:yyyy-MM-dd HH:mm:ss} ~ {1:yyyy-MM-dd HH:mm:ss}", "# Range: {0:yyyy-MM-dd HH:mm:ss} ~ {1:yyyy-MM-dd HH:mm:ss}", "# 照会範囲：{0:yyyy-MM-dd HH:mm:ss} ~ {1:yyyy-MM-dd HH:mm:ss}", "# Intervalo: {0:yyyy-MM-dd HH:mm:ss} ~ {1:yyyy-MM-dd HH:mm:ss}" },
        ["Csv_SumStatus"] = new[] { "# 运行时长：{0}h，报警时长：{1}h，待机时长：{2}h", "# Run: {0}h, Alarm: {1}h, Idle: {2}h", "# 稼働時間：{0}h、アラーム時間：{1}h、待機時間：{2}h", "# Execução: {0}h, Alarme: {1}h, Ocioso: {2}h" },
        ["Csv_TargetCycle"] = new[] { "目标节拍(件/小时)", "Target Cycle (pcs/h)", "目標タクト(個/時)", "Ciclo alvo (peças/h)" },
        ["Csv_Time"] = new[] { "时间", "Time", "時刻", "Hora" },
        ["Csv_Value"] = new[] { "值", "Value", "値", "Valor" },
        ["DefectTop"] = new[] { "缺陷分布 TOP5", "Defect Top 5", "欠陥トップ5", "Defect Top 5" },
        ["Dv_AddressConfig"] = new[] { "地址配置", "Address Config", "アドレス設定", "Address Config" },
        ["Dv_AlarmConfig"] = new[] { "报警配置", "Alarm Config", "警報設定", "Alarm Config" },
        ["Dv_AlarmCount"] = new[] { "报警 {0} 条", "{0} alarms", "警報 {0} 件", "{0} alarms" },
        ["Dv_Category"] = new[] { "类别", "Category", "カテゴリ", "Category" },
        ["Dv_CountAlarmConfig"] = new[] { "计数器报警配置", "Counter Alarm Config", "カウント警報設定", "Counter Alarm Config" },
        ["Dv_CountAlarmCount"] = new[] { "计数器报警 {0} 条", "{0} counter alarms", "カウント警報 {0} 件", "{0} counter alarms" },
        ["Dv_DefectConfig"] = new[] { "缺陷配置", "Defect Config", "欠陥設定", "Defect Config" },
        ["Dv_DefectCount"] = new[] { "缺陷 {0} 条", "{0} defects", "欠陥 {0} 件", "{0} defects" },
        ["Dv_Description"] = new[] { "描述", "Description", "説明", "Description" },
        ["Dv_Detail"] = new[] { "{0} 配置详情", "{0} Config Details", "{0} 設定詳細", "{0} Config Details" },
        ["Dv_DeviceId"] = new[] { "设备 ID", "Device ID", "デバイス ID", "Device ID" },
        ["Dv_LoadFailed"] = new[] { "设备配置加载失败", "Failed to load device configs", "デバイス設定の読み込みに失敗", "Failed to load device configs" },
        ["Dv_LoadFailedHint"] = new[] { "请确认采集服务正常后重试", "Ensure the collection service is running and retry", "収集サービスの稼働を確認して再試行してください", "Ensure the collection service is running and retry" },
        ["Dv_Loading"] = new[] { "正在加载设备配置", "Loading device configs", "デバイス設定を読み込み中", "Loading device configs" },
        ["Dv_MachineType"] = new[] { "机型", "Machine Type", "機種", "Machine Type" },
        ["Dv_Name"] = new[] { "名称", "Name", "名称", "Name" },
        ["Dv_NgCountAddr"] = new[] { "NG 计数地址", "NG Count Address", "NG カウントアドレス", "NG Count Address" },
        ["Dv_NoDevices"] = new[] { "暂无设备配置", "No device configs", "デバイス設定なし", "No device configs" },
        ["Dv_None"] = new[] { "无配置", "None", "設定なし", "None" },
        ["Dv_OkCountAddr"] = new[] { "OK 计数地址", "OK Count Address", "OK カウントアドレス", "OK Count Address" },
        ["Dv_PlcAddr"] = new[] { "PLC 地址", "PLC Address", "PLC アドレス", "PLC Address" },
        ["Dv_ReadOnly"] = new[] { "只读视图 · 写操作请使用 WPF 端", "Read-only · use WPF for edits", "読み取り専用 · 編集は WPF を使用", "Read-only · use WPF for edits" },
        ["Dv_RecipeAddr"] = new[] { "配方地址", "Recipe Address", "レシピアドレス", "Recipe Address" },
        ["Dv_ResetAddr"] = new[] { "产量复位地址", "Reset Address", "リセットアドレス", "Reset Address" },
        ["Dv_Retry"] = new[] { "重试", "Retry", "再試行", "Retry" },
        ["Dv_Severity"] = new[] { "严重度", "Severity", "重大度", "Severity" },
        ["Dv_StatusAddr"] = new[] { "状态字地址", "Status Word Address", "状態語アドレス", "Status Word Address" },
        ["Dv_Threshold"] = new[] { "阈值", "Threshold", "閾値", "Threshold" },
        ["Dv_Title"] = new[] { "设备管理（只读）", "Devices (Read-only)", "デバイス管理（読み取り専用）", "Devices (Read-only)" },
        ["Fresh_Live"] = new[] { "实时", "Live", "リアルタイム", "Live" },
        ["Fresh_Mins"] = new[] { "{0} 分钟前", "{0} min ago", "{0} 分前", "{0} min ago" },
        ["Fresh_None"] = new[] { "未收到", "Not received", "未受信", "Not received" },
        ["Fresh_Secs"] = new[] { "{0} 秒前", "{0}s ago", "{0} 秒前", "{0}s ago" },
        ["Hq_AlarmChart"] = new[] { "报警频次排行（Top 20）", "Alarm Frequency (Top 20)", "アラーム頻度（Top 20）", "Alarm Frequency (Top 20)" },
        ["Hq_AlarmEvents"] = new[] { "报警事件", "Alarm Events", "アラームイベント", "Alarm Events" },
        ["Hq_AlarmHintBody"] = new[] { "选择设备与时间范围后点击“查询”，可查看触发/恢复/待恢复统计、频次排行与事件明细", "Select a device and time range, then click Search for trigger/recover/pending stats, frequency and events", "デバイスと時間範囲を選択して「検索」をクリックすると、発生/復旧/未復旧の統計・頻度・イベントを確認できます", "Select a device and time range, then click Search for trigger/recover/pending stats, frequency and events" },
        ["Hq_AlarmHintTitle"] = new[] { "报警历史查询", "Alarm History Query", "警報履歴照会", "Alarm History Query" },
        ["Hq_AlarmId"] = new[] { "报警 ID", "Alarm ID", "アラーム ID", "Alarm ID" },
        ["Hq_AlarmName"] = new[] { "报警名称", "Alarm Name", "アラーム名", "Alarm Name" },
        ["Hq_AlarmPending"] = new[] { "待恢复", "Pending", "未復旧", "Pending" },
        ["Hq_AlarmPlc"] = new[] { "PLC 地址", "PLC Address", "PLC アドレス", "PLC Address" },
        ["Hq_AlarmRecovered"] = new[] { "恢复", "Recovered", "復旧", "Recovered" },
        ["Hq_AlarmTriggered"] = new[] { "触发", "Triggered", "発生", "Triggered" },
        ["Hq_AlarmType"] = new[] { "事件类型", "Event Type", "イベント種別", "Event Type" },
        ["Hq_AllAlarms"] = new[] { "全部报警", "All Alarms", "全アラーム", "All Alarms" },
        ["Hq_AllDevices"] = new[] { "全部设备", "All Devices", "全デバイス", "All Devices" },
        ["Hq_AllShifts"] = new[] { "全部班次", "All Shifts", "全シフト", "All Shifts" },
        ["Hq_Analyzing"] = new[] { "正在分析产量数据", "Analyzing production data", "生産データを分析中", "Analyzing production data" },
        ["Hq_ChartNg"] = new[] { "NG 产量", "NG Output", "NG 生産量", "NG Output" },
        ["Hq_ChartOk"] = new[] { "OK 产量", "OK Output", "OK 生産量", "OK Output" },
        ["Hq_ChartTitle"] = new[] { "产量趋势（15 分钟分桶）", "Production Trend (15-min buckets)", "生産トレンド（15分バケット）", "Production Trend (15-min buckets)" },
        ["Hq_CurrState"] = new[] { "当前状态", "Current State", "現在の状態", "Current State" },
        ["Hq_Custom"] = new[] { "自定义", "Custom", "カスタム", "Custom" },
        ["Hq_Device"] = new[] { "设备", "Device", "デバイス", "Device" },
        ["Hq_DeviceId"] = new[] { "设备 ID", "Device ID", "デバイス ID", "Device ID" },
        ["Hq_DeviceName"] = new[] { "设备名称", "Device Name", "デバイス名", "Device Name" },
        ["Hq_EventTime"] = new[] { "事件时间", "Event Time", "イベント時刻", "Event Time" },
        ["Hq_Export"] = new[] { "导出 CSV", "Export CSV", "CSV エクスポート", "Export CSV" },
        ["Hq_ExportEmpty"] = new[] { "当前页无数据可导出", "Nothing to export on this page", "このページにエクスポート対象がありません", "Nothing to export on this page" },
        ["Hq_From"] = new[] { "开始", "From", "開始", "From" },
        ["Hq_HintBody"] = new[] { "选择设备与时间范围后点击“查询”，可查看 KPI、15 分钟产量趋势与明细", "Select a device and time range, then click Search for KPI, 15-min trend and details", "デバイスと時間範囲を選択して「検索」をクリックすると、KPI・15分トレンド・明細を確認できます", "Select a device and time range, then click Search for KPI, 15-min trend and details" },
        ["Hq_HintTitle"] = new[] { "产量历史查询", "Production History Query", "生産履歴照会", "Production History Query" },
        ["Hq_InsAlarmChain"] = new[] { "连锁触发模式 {0} 出现 {1} 次", "Chain trigger pattern {0} x{1}", "連鎖発生パターン {0} が {1} 回", "Chain trigger pattern {0} x{1}" },
        ["Hq_InsAlarmPending"] = new[] { "待恢复报警：{0}", "Pending alarms: {0}", "未復旧警報：{0}", "Pending alarms: {0}" },
        ["Hq_InsAlarmPendingItem"] = new[] { "{0}（{1}，自 {2}）", "{0} ({1}, since {2})", "{0}（{1}、{2} から）", "{0} ({1}, since {2})" },
        ["Hq_InsAlarmRatio"] = new[] { "报警占比 {0:P0}，超过阈值 {1:P0}", "Alarm ratio {0:P0}, above threshold {1:P0}", "警報割合 {0:P0}、閾値 {1:P0} 超", "Alarm ratio {0:P0}, above threshold {1:P0}" },
        ["Hq_InsAlarmTop"] = new[] { "{0}（{1} 次，占 {2:P0}）", "{0} ({1} times, {2:P0})", "{0}（{1} 回、{2:P0}）", "{0} ({1} times, {2:P0})" },
        ["Hq_InsAlarmTop3"] = new[] { "报警频次 TOP3：{0}", "Alarm frequency TOP3: {0}", "警報頻度 TOP3：{0}", "Alarm frequency TOP3: {0}" },
        ["Hq_InsLongestAlarm"] = new[] { "最长连续报警 {0} 分钟（{1} ~ {2}）", "Longest alarm {0} min ({1} ~ {2})", "最長連続警報 {0} 分（{1} ~ {2}）", "Longest alarm {0} min ({1} ~ {2})" },
        ["Hq_InsLongestAlarmLong"] = new[] { "⚠ 单次报警超 30 分钟：最长 {0} 分钟（{1} ~ {2}）", "⚠ Alarm over 30 min: longest {0} min ({1} ~ {2})", "⚠ 30分超の警報：最長 {0} 分（{1} ~ {2}）", "⚠ Alarm over 30 min: longest {0} min ({1} ~ {2})" },
        ["Hq_InsLongestPause"] = new[] { "最长连续待机 {0} 分钟（{1} ~ {2}）", "Longest pause {0} min ({1} ~ {2})", "最長連続待機 {0} 分（{1} ~ {2}）", "Longest pause {0} min ({1} ~ {2})" },
        ["Hq_InsLongestRun"] = new[] { "最长连续运行 {0} 分钟（{1} ~ {2}）", "Longest run {0} min ({1} ~ {2})", "最長連続稼働 {0} 分（{1} ~ {2}）", "Longest run {0} min ({1} ~ {2})" },
        ["Hq_InsOeeBalance"] = new[] { "合格率 {0:P0} × 性能率 {1:P0} × 可用率 {2:P0} = OEE {3:P0}", "Quality {0:P0} × Performance {1:P0} × Availability {2:P0} = OEE {3:P0}", "良品率 {0:P0} × 性能率 {1:P0} × 稼働率 {2:P0} = OEE {3:P0}", "Quality {0:P0} × Performance {1:P0} × Availability {2:P0} = OEE {3:P0}" },
        ["Hq_InsOeeGap"] = new[] { "{0}（{1:P0}）领先 {2}（{3:P0}）", "{0} ({1:P0}) leads {2} ({3:P0})", "{0}（{1:P0}）が {2}（{3:P0}）より高い", "{0} ({1:P0}) leads {2} ({3:P0})" },
        ["Hq_InsOeeWeak"] = new[] { "{0} 偏低（{1:P0}），是 OEE 短板", "{0} is low ({1:P0}), the OEE bottleneck", "{0} が低い（{1:P0}）、OEE の足を引っ張る要因", "{0} is low ({1:P0}), the OEE bottleneck" },
        ["Hq_InsPauseRatio"] = new[] { "待机占比 {0:P0}，超过阈值 {1:P0}", "Paused ratio {0:P0}, above threshold {1:P0}", "待機割合 {0:P0}、閾値 {1:P0} 超", "Paused ratio {0:P0}, above threshold {1:P0}" },
        ["Hq_InsShiftDrag"] = new[] { "主要拖累：{0}（{1:P0} vs 最佳 {2:P0}）", "Main drag: {0} ({1:P0} vs best {2:P0})", "主な原因：{0}（{1:P0} vs 最高 {2:P0}）", "Main drag: {0} ({1:P0} vs best {2:P0})" },
        ["Hq_InsShiftWorst"] = new[] { "班次 {0}（{1}）OEE {2:P0} 最低，与最佳班次差距 {3:P0}", "Shift {0} ({1}) has lowest OEE {2:P0}, {3:P0} behind the best", "シフト {0}（{1}）の OEE {2:P0} が最低、最高シフトより {3:P0} 低い", "Shift {0} ({1}) has lowest OEE {2:P0}, {3:P0} behind the best" },
        ["Hq_InsightDrop"] = new[] { "检测到 {0} 次突降，最严重 {1} 下降 {2:P0}（{3} → {4} 件）", "{0} sudden drop(s), worst {1} -{2:P0} ({3} → {4} pcs)", "急落 {0} 回、最悪 {1} -{2:P0}（{3} → {4} 個）", "{0} sudden drop(s), worst {1} -{2:P0} ({3} → {4} pcs)" },
        ["Hq_InsightPeakHigh"] = new[] { "峰值 {0} 件（{1}），高于均值 {2:P0}", "Peak {0} ({1}), {2:P0} above avg", "ピーク {0} 個（{1}）、平均より {2:P0} 高い", "Peak {0} ({1}), {2:P0} above avg" },
        ["Hq_InsightPeakLow"] = new[] { "峰值 {0} 件（{1}），低于均值 {2:P0}", "Peak {0} ({1}), {2:P0} below avg", "ピーク {0} 個（{1}）、平均より {2:P0} 低い", "Peak {0} ({1}), {2:P0} below avg" },
        ["Hq_InsightSteady"] = new[] { "平均 {0} 件/桶，峰值 {1} 件（{2}），产量平稳", "Avg {0}/bucket, peak {1} ({2}), steady output", "平均 {0} 個/バケット、ピーク {1} 個（{2}）、安定", "Avg {0}/bucket, peak {1} ({2}), steady output" },
        ["Hq_Last30d"] = new[] { "近 30 天", "Last 30 Days", "直近30日", "Last 30 Days" },
        ["Hq_Last7d"] = new[] { "近 7 天", "Last 7 Days", "直近7日", "Last 7 Days" },
        ["Hq_Loading"] = new[] { "查询中", "Querying", "照会中", "Querying" },
        ["Hq_NeedDevice"] = new[] { "请先选择设备（该 Tab 按单设备查询）", "Select a device first (this tab queries one device)", "先にデバイスを選択してください（このタブは単一デバイス照会）", "Select a device first (this tab queries one device)" },
        ["Hq_NextPage"] = new[] { "下一页", "Next", "次へ", "Next" },
        ["Hq_NgCol"] = new[] { "NG", "NG", "NG", "NG" },
        ["Hq_NoData"] = new[] { "暂无数据", "No Data", "データなし", "No Data" },
        ["Hq_NoDataHint"] = new[] { "请调整时间范围或设备筛选后重试", "Adjust the time range or device filter and retry", "時間範囲またはデバイス条件を変更して再試行してください", "Adjust the time range or device filter and retry" },
        ["Hq_OeeDetails"] = new[] { "班次 OEE 明细", "Shift OEE Details", "シフト OEE 明細", "Shift OEE Details" },
        ["Hq_OeeHintBody"] = new[] { "选择设备与时间范围后点击“查询”，可查看四率、班次 OEE 趋势与明细", "Select a device and time range, then click Search for the four rates, shift OEE trend and details", "デバイスと時間範囲を選択して「検索」をクリックすると、四率・シフト OEE トレンド・明細を確認できます", "Select a device and time range, then click Search for the four rates, shift OEE trend and details" },
        ["Hq_OeeHintTitle"] = new[] { "OEE 历史查询", "OEE History Query", "OEE 履歴照会", "OEE History Query" },
        ["Hq_OeeOverview"] = new[] { "OEE 综合概览", "Overall OEE", "OEE 総合", "Overall OEE" },
        ["Hq_OeeTrend"] = new[] { "班次 OEE 趋势", "Shift OEE Trend", "シフト OEE トレンド", "Shift OEE Trend" },
        ["Hq_OkCol"] = new[] { "OK", "OK", "OK", "OK" },
        ["Hq_PageInfo"] = new[] { "第 {0} / {1} 页 · 共 {2} 条", "Page {0} / {1} · {2} rows", "{0} / {1} ページ · 全 {2} 件", "Page {0} / {1} · {2} rows" },
        ["Hq_PrevPage"] = new[] { "上一页", "Prev", "前へ", "Prev" },
        ["Hq_PrevState"] = new[] { "前一状态", "Previous State", "前状態", "Previous State" },
        ["Hq_QualityRate"] = new[] { "合格率", "Quality Rate", "良品率", "Quality Rate" },
        ["Hq_QueryFailed"] = new[] { "查询失败，请确认采集服务正常后重试", "Query failed. Ensure the collection service is running", "照会に失敗しました。収集サービスの稼働を確認してください", "Query failed. Ensure the collection service is running" },
        ["Hq_QuickRange"] = new[] { "快捷时间", "Quick Range", "クイック範囲", "Quick Range" },
        ["Hq_Reset"] = new[] { "重置", "Reset", "リセット", "Reset" },
        ["Hq_Search"] = new[] { "查询", "Search", "検索", "Search" },
        ["Hq_Shift"] = new[] { "班次", "Shift", "シフト", "Shift" },
        ["Hq_ShiftChange"] = new[] { "班次切换", "Shift Change", "シフト切替", "Shift Change" },
        ["Hq_ShiftTime"] = new[] { "开始时间", "Start Time", "開始時刻", "Start Time" },
        ["Hq_StateUnknown"] = new[] { "离线", "Offline", "オフライン", "Offline" },
        ["Hq_StatusAlarm"] = new[] { "报警时长", "Alarm Time", "アラーム時間", "Alarm Time" },
        ["Hq_StatusDaily"] = new[] { "每日状态时长（小时）", "Daily State Hours", "日別状態時間（時間）", "Daily State Hours" },
        ["Hq_StatusGantt"] = new[] { "状态甘特图", "Status Gantt", "状態ガントチャート", "Status Gantt" },
        ["Hq_StatusHintBody"] = new[] { "选择设备与时间范围后点击“查询”，可查看状态时长占比、每日分布、甘特图与转换明细", "Select a device and time range, then click Search for state durations, daily distribution, gantt and transitions", "デバイスと時間範囲を選択して「検索」をクリックすると、状態時間・日別分布・ガントチャート・遷移明細を確認できます", "Select a device and time range, then click Search for state durations, daily distribution, gantt and transitions" },
        ["Hq_StatusHintTitle"] = new[] { "状态历史查询", "Status History Query", "状態履歴照会", "Status History Query" },
        ["Hq_StatusPause"] = new[] { "待机时长", "Paused Time", "待機時間", "Paused Time" },
        ["Hq_StatusPie"] = new[] { "状态时长占比", "State Duration Share", "状態時間割合", "State Duration Share" },
        ["Hq_StatusRun"] = new[] { "运行时长", "Run Time", "稼働時間", "Run Time" },
        ["Hq_StatusTransitions"] = new[] { "状态转换记录", "Status Transitions", "状態遷移記録", "Status Transitions" },
        ["Hq_StatusWord"] = new[] { "状态字", "Status Word", "状態語", "Status Word" },
        ["Hq_ThisMonth"] = new[] { "本月", "This Month", "今月", "This Month" },
        ["Hq_ThisWeek"] = new[] { "本周", "This Week", "今週", "This Week" },
        ["Hq_Time"] = new[] { "时间", "Time", "時間", "Time" },
        ["Hq_To"] = new[] { "结束", "To", "終了", "To" },
        ["Hq_Today"] = new[] { "今天", "Today", "今日", "Today" },
        ["Hq_TotalNg"] = new[] { "总 NG", "Total NG", "NG 合計", "Total NG" },
        ["Hq_TotalOk"] = new[] { "总 OK", "Total OK", "OK 合計", "Total OK" },
        ["Hq_Truncated"] = new[] { "数据量超过 10 万条上限，KPI/图表基于已取部分数据（建议缩小时间范围）", "Over 100k rows; KPI/chart based on fetched subset (narrow the time range)", "10万件超のため、KPI・グラフは取得済みデータに基づきます（時間範囲を絞ってください）", "Over 100k rows; KPI/chart based on fetched subset (narrow the time range)" },
        ["Hq_ValidationRange"] = new[] { "请检查开始/结束时间（格式 yyyy-MM-ddTHH:mm，且开始不得晚于结束）", "Check from/to (format yyyy-MM-ddTHH:mm, from must not be later than to)", "開始/終了時刻を確認してください（形式 yyyy-MM-ddTHH:mm、開始は終了より後にできません）", "Check from/to (format yyyy-MM-ddTHH:mm, from must not be later than to)" },
        ["Hq_Yesterday"] = new[] { "昨天", "Yesterday", "昨日", "Yesterday" },
        ["LastShift"] = new[] { "上一班次", "Last Shift", "前シフト", "Last Shift" },
        ["LastShiftLine"] = new[] { "{0}：OK {1}（{2}）· NG {3}（{4}）", "{0}: OK {1} ({2}) · NG {3} ({4})", "{0}：OK {1}（{2}）· NG {3}（{4}）", "{0}: OK {1} ({2}) · NG {3} ({4})" },
        ["Lbl_Achievement"] = new[] { "达成率", "Achievement", "達成率", "Achievement" },
        ["Lbl_ActualCycle"] = new[] { "实际节拍", "Actual Cycle", "実タクト", "Actual Cycle" },
        ["Lbl_Availability"] = new[] { "可用率", "Availability", "稼働率", "Availability" },
        ["Lbl_ConnStatus"] = new[] { "连接状态", "Connection", "接続状態", "Connection" },
        ["Lbl_DataFresh"] = new[] { "数据更新", "Data Freshness", "データ更新", "Data Freshness" },
        ["Lbl_DevTotal"] = new[] { "设备总数", "Total Devices", "デバイス総数", "Total Devices" },
        ["Lbl_Elapsed"] = new[] { "已运行", "Elapsed", "稼働時間", "Elapsed" },
        ["Lbl_Ng"] = new[] { "NG 不良", "NG Defect", "NG 不良", "NG Defect" },
        ["Lbl_NgRate"] = new[] { "不良率", "NG Rate", "不良率", "NG Rate" },
        ["Lbl_Ok"] = new[] { "OK 良品", "OK Good", "OK 良品", "OK Good" },
        ["Lbl_Performance"] = new[] { "性能率", "Performance", "性能率", "Performance" },
        ["Lbl_Quality"] = new[] { "合格率", "Quality", "良品率", "Quality" },
        ["Lbl_RealTimeSpeed"] = new[] { "实时速度（件/小时）", "Real-time Speed (pcs/h)", "リアルタイム速度（個/時）", "Real-time Speed (pcs/h)" },
        ["Lbl_Remaining"] = new[] { "剩余", "Remaining", "残り", "Remaining" },
        ["Lbl_SnapSeq"] = new[] { "快照序号", "Snapshot Seq", "スナップショット番号", "Snapshot Seq" },
        ["Lbl_SvcAddr"] = new[] { "服务地址", "Service Address", "サービスアドレス", "Service Address" },
        ["Lbl_SvcVersion"] = new[] { "服务版本", "Service Version", "サービスバージョン", "Service Version" },
        ["Lbl_TargetCycle"] = new[] { "目标节拍", "Target Cycle", "目標タクト", "Target Cycle" },
        ["Lbl_TotalOutput"] = new[] { "总产量", "Total Output", "総生産量", "Total Output" },
        ["Ln_CurrentShift"] = new[] { "当前班次", "Current Shift", "現在のシフト", "Current Shift" },
        ["Ln_Cycle"] = new[] { "节拍（实际/目标）", "Cycle (Actual/Target)", "タクト（実績/目標）", "Cycle (Actual/Target)" },
        ["Ln_DevCount"] = new[] { "共 {0} 台设备", "{0} devices", "デバイス {0} 台", "{0} devices" },
        ["Ln_Downtime"] = new[] { "停机", "Downtime", "停止", "Downtime" },
        ["Ln_EmptyFilter"] = new[] { "没有匹配的设备", "No matching devices", "一致するデバイスがありません", "No matching devices" },
        ["Ln_FilterAll"] = new[] { "全部状态", "All Statuses", "全状態", "All Statuses" },
        ["Ln_NoDevices"] = new[] { "暂无设备", "No devices", "デバイスなし", "No devices" },
        ["Ln_NoDevicesHint"] = new[] { "请确认采集服务与仿真器已启动", "Ensure the collection service and simulator are running", "収集サービスとシミュレーターの起動を確認してください", "Ensure the collection service and simulator are running" },
        ["Ln_Search"] = new[] { "搜索设备", "Search devices", "デバイス検索", "Search devices" },
        ["Ln_ShiftProgress"] = new[] { "班次进度", "Shift Progress", "シフト進捗", "Shift Progress" },
        ["Ln_SortName"] = new[] { "按名称", "By Name", "名前順", "By Name" },
        ["Ln_SortOee"] = new[] { "按 OEE", "By OEE", "OEE 順", "By OEE" },
        ["Ln_SortOutput"] = new[] { "按产量", "By Output", "生産順", "By Output" },
        ["Ln_Title"] = new[] { "产线总览", "Production Line Overview", "生産ライン概要", "Production Line Overview" },
        ["Ln_WeightedOee"] = new[] { "加权 OEE", "Weighted OEE", "加重 OEE", "Weighted OEE" },
        ["Meta_PlanWo"] = new[] { "计划 {0} 件", "Planned {0} pcs", "計画 {0} 個", "Planned {0} pcs" },
        ["Meta_QualityRate"] = new[] { "合格率 {0} · 不良率 {1}", "Quality {0} · NG rate {1}", "良品率 {0} · 不良率 {1}", "Quality {0} · NG rate {1}" },
        ["Meta_ShiftAuto"] = new[] { "按班次配置自动计算", "Auto-calculated from shift config", "シフト設定から自動計算", "Auto-calculated from shift config" },
        ["Meta_StatusWord"] = new[] { "状态字 0x{0} · 目标 {1} 件/h", "Status word 0x{0} · Target {1} pcs/h", "状態語 0x{0} · 目標 {1} 個/h", "Status word 0x{0} · Target {1} pcs/h" },
        ["Meta_TrendCurrent"] = new[] { "当前 {0} 件/h · 采样 0.5s", "Current {0} pcs/h · Sampling 0.5s", "現在 {0} 個/h · サンプリング 0.5秒", "Current {0} pcs/h · Sampling 0.5s" },
        ["Mo_AcqRunning"] = new[] { "采集中", "Acquiring", "収集中", "Acquiring" },
        ["Mo_AcqStatus"] = new[] { "采集状态", "Acquisition", "収集状態", "Acquisition" },
        ["Mo_AcqStopped"] = new[] { "已停止", "Stopped", "停止中", "Stopped" },
        ["Mo_AvgCycleMs"] = new[] { "平均循环耗时", "Avg Cycle", "平均サイクル", "Avg Cycle" },
        ["Mo_CompletedCycles"] = new[] { "完成循环", "Completed Cycles", "完了サイクル", "Completed Cycles" },
        ["Mo_ConsecutiveFail"] = new[] { "连续失败", "Consecutive Failures", "連続失敗", "Consecutive Failures" },
        ["Mo_CycleHealth"] = new[] { "采集循环健康", "Acquisition Cycle Health", "収集サイクル健全性", "Acquisition Cycle Health" },
        ["Mo_DbSize"] = new[] { "数据库大小", "DB Size", "DB サイズ", "DB Size" },
        ["Mo_DeviceLive"] = new[] { "设备实时状态", "Live Device Status", "デバイスリアルタイム状態", "Live Device Status" },
        ["Mo_DevicesRead"] = new[] { "设备读取", "Devices Read", "デバイス読取", "Devices Read" },
        ["Mo_Disconnects"] = new[] { "断连次数", "Disconnects", "切断回数", "Disconnects" },
        ["Mo_EstimatedOps"] = new[] { "估算读操作", "Est. Read Ops", "推定読取回数", "Est. Read Ops" },
        ["Mo_FailedCycles"] = new[] { "失败循环", "Failed Cycles", "失敗サイクル", "Failed Cycles" },
        ["Mo_FlushFailures"] = new[] { "落库失败", "Flush Failures", "書込失敗", "Flush Failures" },
        ["Mo_HistoryHealth"] = new[] { "历史落库健康", "History Persistence", "履歴保存健全性", "History Persistence" },
        ["Mo_LastCycleMs"] = new[] { "最近循环耗时", "Last Cycle", "直近サイクル", "Last Cycle" },
        ["Mo_LastFailureAt"] = new[] { "上次失败", "Last Failure", "最終失敗", "Last Failure" },
        ["Mo_LastFlushAt"] = new[] { "上次落库", "Last Flush", "最終書込", "Last Flush" },
        ["Mo_LastSuccessAt"] = new[] { "上次成功", "Last Success", "最終成功", "Last Success" },
        ["Mo_Live3s"] = new[] { "3s 刷新", "Refresh 3s", "3秒更新", "Refresh 3s" },
        ["Mo_MaxCycleMs"] = new[] { "最大循环耗时", "Max Cycle", "最大サイクル", "Max Cycle" },
        ["Mo_PendingHistory"] = new[] { "历史积压", "History Backlog", "履歴滞留", "History Backlog" },
        ["Mo_RecoveryFile"] = new[] { "恢复文件", "Recovery File", "リカバリファイル", "Recovery File" },
        ["Mo_Refresh10s"] = new[] { "10s 刷新", "Refresh 10s", "10秒更新", "Refresh 10s" },
        ["Mo_SuccessRate"] = new[] { "采集成功率", "Cycle Success Rate", "サイクル成功率", "Cycle Success Rate" },
        ["Mo_TimingBreakdown"] = new[] { "读取耗时分解（ms）", "Read Timing Breakdown (ms)", "読取時間内訳（ms）", "Read Timing Breakdown (ms)" },
        ["Mo_TmAlarm"] = new[] { "报警", "Alarm", "警報", "Alarm" },
        ["Mo_TmBatchPlan"] = new[] { "批计划", "Batch Plan", "バッチ計画", "Batch Plan" },
        ["Mo_TmCountAlarm"] = new[] { "计数器报警", "Counter Alarm", "カウント警報", "Counter Alarm" },
        ["Mo_TmDefect"] = new[] { "缺陷", "Defect", "欠陥", "Defect" },
        ["Mo_TmDword"] = new[] { "字读取", "DWord Read", "ワード読取", "DWord Read" },
        ["Mo_TmHistory"] = new[] { "历史写入", "History Write", "履歴書込", "History Write" },
        ["Msg_EmptyHint"] = new[] { "确认 PlcSimulator 与 Kanban.Collector 已启动，且 CollectorHubUrl 端口一致", "Ensure PlcSimulator and Kanban.Collector are running and the CollectorHubUrl port matches", "PlcSimulator と Kanban.Collector が起動し、CollectorHubUrl のポートが一致していることを確認してください", "Ensure PlcSimulator and Kanban.Collector are running and the CollectorHubUrl port matches" },
        ["Msg_NoDevSelected"] = new[] { "未选择设备", "No device selected", "デバイス未選択", "No device selected" },
        ["Msg_NoDeviceData"] = new[] { "暂无设备数据", "No device data", "デバイスデータなし", "No device data" },
        ["Msg_SelectHint"] = new[] { "从右上角选择要查看的设备", "Select a device from the top right", "右上から表示するデバイスを選択してください", "Select a device from the top right" },
        ["Msg_WaitingConn"] = new[] { "等待连接采集服务…", "Waiting for the collection service…", "収集サービスへの接続待ち…", "Waiting for the collection service…" },
        ["Nav_AlarmCenter"] = new[] { "报警中心", "Alarm Center", "警報センター", "Alarm Center" },
        ["Nav_Audit"] = new[] { "审计", "Audit", "監査", "Audit" },
        ["Nav_Dashboard"] = new[] { "看板", "Dashboard", "ダッシュボード", "Dashboard" },
        ["Nav_Devices"] = new[] { "设备", "Devices", "デバイス", "Devices" },
        ["Nav_History"] = new[] { "历史查询", "History Query", "履歴照会", "History Query" },
        ["Nav_Line"] = new[] { "产线预览", "Production Line", "生産ライン", "Production Line" },
        ["Nav_Monitoring"] = new[] { "运行监控", "Runtime Monitoring", "稼働監視", "Runtime Monitoring" },
        ["Nav_Recipes"] = new[] { "配方", "Recipes", "レシピ", "Recipes" },
        ["Nav_Review"] = new[] { "生产复盘", "Production Review", "生産レビュー", "Production Review" },
        ["Nav_Settings"] = new[] { "设置", "Settings", "設定", "Settings" },
        ["Nav_WorkOrders"] = new[] { "工单", "Work Orders", "工単", "Work Orders" },
        ["NoDefectData"] = new[] { "暂无缺陷数据", "No defect data", "欠陥データなし", "No defect data" },
        ["Rc_ItemCount"] = new[] { "{0} 个参数", "{0} params", "{0} パラメータ", "{0} params" },
        ["Rc_None"] = new[] { "暂无配方", "No recipes", "レシピなし", "No recipes" },
        ["Rc_Title"] = new[] { "配方管理（只读）", "Recipes (Read-only)", "レシピ管理（読み取り専用）", "Recipes (Read-only)" },
        ["Recipe"] = new[] { "配方", "Recipe", "レシピ", "Recipe" },
        ["RecipeInfo"] = new[] { "配方 {0}：{1}", "Recipe {0}: {1}", "レシピ {0}：{1}", "Recipe {0}: {1}" },
        ["Rv_AlarmCol"] = new[] { "报警", "Alarms", "警報", "Alarms" },
        ["Rv_AlarmCount"] = new[] { "报警次数", "Alarm Count", "警報回数", "Alarm Count" },
        ["Rv_AlarmCountConclusion"] = new[] { "当前范围共触发 {0:N0} 次报警，请结合 Top 5 报警确认主要停机来源", "{0:N0} alarms triggered; check Top 5 alarms for downtime sources", "この期間に警報 {0:N0} 回発生、Top5 警報で停止要因を確認してください", "{0:N0} alarms triggered; check Top 5 alarms for downtime sources" },
        ["Rv_AlarmRank"] = new[] { "报警排行（Top 5）", "Alarm Ranking (Top 5)", "警報ランキング（Top 5）", "Alarm Ranking (Top 5)" },
        ["Rv_BaselineOee"] = new[] { "上一周期 OEE", "Previous OEE", "前周期の OEE", "Previous OEE" },
        ["Rv_BaselineOutput"] = new[] { "上一周期产量", "Previous Output", "前周期の生産", "Previous Output" },
        ["Rv_BaselineQuality"] = new[] { "上一周期良品率", "Previous Quality", "前周期の良品率", "Previous Quality" },
        ["Rv_BestShiftConclusion"] = new[] { "{0}产量最高，共 {1:N0} 件，良品率 {2:P1}", "{0} has the highest output ({1:N0} pcs), quality {2:P1}", "{0} の生産が最多（{1:N0} 個）、良品率 {2:P1}", "{0} has the highest output ({1:N0} pcs), quality {2:P1}" },
        ["Rv_Comparison"] = new[] { "周期对比", "Period Comparison", "期間比較", "Period Comparison" },
        ["Rv_ComparisonHint"] = new[] { "当前设备与上一周期的变化", "Changes vs the previous period", "前周期との変化", "Changes vs the previous period" },
        ["Rv_Conclusions"] = new[] { "复盘结论", "Conclusions", "レビュー結論", "Conclusions" },
        ["Rv_ConclusionsHint"] = new[] { "基于当前生产、设备与质量数据生成", "Generated from production, device and quality data", "生産・設備・品質データから生成", "Generated from production, device and quality data" },
        ["Rv_CurrentOutput"] = new[] { "当前总产量", "Current Output", "今回の総生産", "Current Output" },
        ["Rv_CurrentShift"] = new[] { "当前班次", "Current Shift", "現在のシフト", "Current Shift" },
        ["Rv_DowntimeConclusion"] = new[] { "最长停机为 {0:F1} 小时，设备：{1}，报警：{2}", "Longest downtime {0:F1} h, device: {1}, alarm: {2}", "最長停止 {0:F1} 時間、設備：{1}、警報：{2}", "Longest downtime {0:F1} h, device: {1}, alarm: {2}" },
        ["Rv_Health"] = new[] { "设备健康评分", "Device Health", "デバイス健康スコア", "Device Health" },
        ["Rv_HealthAlarmSpike"] = new[] { "报警突增：当前 {0} 次，上一周期 {1} 次", "Alarm spike: {0} now vs {1} last period", "警報急増：今回 {0} 回、前周期 {1} 回", "Alarm spike: {0} now vs {1} last period" },
        ["Rv_HealthDefectSpike"] = new[] { "缺陷率突增：当前 {0} 个，上一周期 {1} 个", "Defect spike: {0} now vs {1} last period", "欠陥急増：今回 {0} 個、前周期 {1} 個", "Defect spike: {0} now vs {1} last period" },
        ["Rv_HealthLowOutput"] = new[] { "节拍异常：实际 {0:F1} 件/小时，低于目标 {1:F0} 件/小时的 80%", "Cycle anomaly: actual {0:F1} pcs/h, target {1:F0} pcs/h, below 80%", "タクト異常：実績 {0:F1} 個/時、目標 {1:F0} 個/時の 80%", "Anomalia de ciclo: real {0:F1} pcs/h, meta {1:F0} pcs/h, abaixo de 80%" },
        ["Rv_HealthNoOutput"] = new[] { "运行无产量：{0}-{1} 持续 {2:F0} min", "Running with no output: {0}-{1} for {2:F0} min", "稼働中に生産なし：{0}-{1} で {2:F0} 分", "Running with no output: {0}-{1} for {2:F0} min" },
        ["Rv_HintBody"] = new[] { "选择设备与时间范围后点击“查询”，生成健康评分、复盘结论与周期对比", "Select a device and time range, then click Search for health score, conclusions and period comparison", "デバイスと時間範囲を選択して「検索」をクリックすると、健康スコア・結論・期間比較を確認できます", "Select a device and time range, then click Search for health score, conclusions and period comparison" },
        ["Rv_HintTitle"] = new[] { "生产复盘分析", "Production Review", "生産レビュー分析", "Production Review" },
        ["Rv_LongestDowntime"] = new[] { "最长停机", "Longest Downtime", "最長停止", "Longest Downtime" },
        ["Rv_Met"] = new[] { "达到", "Met", "達成", "Met" },
        ["Rv_NoConclusion"] = new[] { "当前时间范围没有足够的产量或报警数据生成复盘结论", "Not enough output or alarm data in this range to generate conclusions", "この期間には結論を生成するのに十分な生産・警報データがありません", "Not enough output or alarm data in this range to generate conclusions" },
        ["Rv_NoIssues"] = new[] { "未发现健康问题", "No health issues found", "健康上の問題なし", "No health issues found" },
        ["Rv_NotMet"] = new[] { "低于", "Below", "未達", "Below" },
        ["Rv_OeeConclusion"] = new[] { "OEE 为 {0:P1}，{1} {2:P0} 目标", "OEE is {0:P1}, {1} the {2:P0} target", "OEE {0:P1}、目標 {2:P0} を{1}", "OEE is {0:P1}, {1} the {2:P0} target" },
        ["Rv_OutputAchievement"] = new[] { "节拍达成", "Cycle Achievement", "タクト達成", "Cycle Achievement" },
        ["Rv_PeakHour"] = new[] { "峰值时段", "Peak Hour", "ピーク時間帯", "Peak Hour" },
        ["Rv_PeakValleyOk"] = new[] { "OK {0} 件 · 占 {1:P0}", "OK {0} pcs · {1:P0} share", "OK {0} 個 · {1:P0} の割合", "OK {0} pcs · {1:P0} share" },
        ["Rv_Product"] = new[] { "产品 / 批次", "Product / Batch", "製品 / ロット", "Product / Batch" },
        ["Rv_QualityConclusion"] = new[] { "良品率为 {0:P1}，{1} {2:P0} 目标", "Quality is {0:P1}, {1} the {2:P0} target", "良品率 {0:P1}、目標 {2:P0} を{1}", "Quality is {0:P1}, {1} the {2:P0} target" },
        ["Rv_Recipe"] = new[] { "当前配方", "Current Recipe", "現在のレシピ", "Current Recipe" },
        ["Rv_RecipeHint"] = new[] { "配方值来自当前设备配置", "Recipe value from device config", "レシピ値はデバイス設定から", "Recipe value from device config" },
        ["Rv_ShiftDetails"] = new[] { "班次明细", "Shift Details", "シフト明細", "Shift Details" },
        ["Rv_Timeline"] = new[] { "设备状态时间线", "Status Timeline", "状態タイムライン", "Status Timeline" },
        ["Rv_TimelineHint"] = new[] { "运行、报警、待机与未知区间；悬浮查看该段产量与报警", "Run, alarm, pause and unknown segments; hover for output and alarms", "稼働・警報・待機・不明区間。ホバーで生産と警報を確認", "Run, alarm, pause and unknown segments; hover for output and alarms" },
        ["Rv_TopDefectConclusion"] = new[] { "主要缺陷为 {0}（{1}），当前累计 {2:N0} 件，占当前缺陷 Top10 的 {3:F1}%", "Top defect: {0} ({1}), {2:N0} pcs, {3:F1}%", "主要欠陥は {0}（{1}）、累計 {2:N0} 個、Top10 の {3:F1}%", "Defeito principal: {0} ({1}), {2:N0} pcs, {3:F1}%" },
        ["Rv_Trend"] = new[] { "产量趋势", "Output Trend", "生産トレンド", "Output Trend" },
        ["Rv_ValleyHour"] = new[] { "谷值时段", "Valley Hour", "ボトム時間帯", "Valley Hour" },
        ["Rv_WorkOrder"] = new[] { "当前工单", "Current Work Order", "現在の工単", "Current Work Order" },
        ["St_Acquisition"] = new[] { "采集参数", "Acquisition", "収集パラメータ", "Acquisition" },
        ["St_AddrZero"] = new[] { "地址从 0 开始", "Zero-based Addr", "0 起点アドレス", "Zero-based Addr" },
        ["St_BatchGapSlots"] = new[] { "批读最大间隙", "Batch Read Gap", "バッチ読取ギャップ", "Batch Read Gap" },
        ["St_BatchMaxLen"] = new[] { "批读最大长度", "Batch Read Max", "バッチ読取最大長", "Batch Read Max" },
        ["St_DataFormat"] = new[] { "数据格式", "Data Format", "データ形式", "Data Format" },
        ["St_HistoryScans"] = new[] { "历史写入间隔（扫描次）", "History Write (scans)", "履歴書込間隔（スキャン）", "History Write (scans)" },
        ["St_NoShifts"] = new[] { "未配置班次", "No shifts configured", "シフト未設定", "No shifts configured" },
        ["St_Plc"] = new[] { "PLC 连接", "PLC Connection", "PLC 接続", "PLC Connection" },
        ["St_PlcBrand"] = new[] { "PLC 品牌", "PLC Brand", "PLC ブランド", "PLC Brand" },
        ["St_PlcIp"] = new[] { "IP 地址", "IP Address", "IP アドレス", "IP Address" },
        ["St_PlcPort"] = new[] { "端口", "Port", "ポート", "Port" },
        ["St_PlcTimeout"] = new[] { "超时", "Timeout", "タイムアウト", "Timeout" },
        ["St_PollingMs"] = new[] { "轮询间隔", "Polling Interval", "ポーリング間隔", "Polling Interval" },
        ["St_ReadSplits"] = new[] { "读取分段", "Read Splits", "読取分割", "Read Splits" },
        ["St_Shifts"] = new[] { "班次配置", "Shift Config", "シフト設定", "Shift Config" },
        ["St_SiemensModel"] = new[] { "机型", "Model", "機種", "Model" },
        ["St_Title"] = new[] { "采集设置（只读）", "Settings (Read-only)", "収集設定（読み取り専用）", "Settings (Read-only)" },
        ["Status_Alarm"] = new[] { "报警", "Alarm", "アラーム", "Alarme" },
        ["Status_Idle"] = new[] { "空闲", "Idle", "アイドル", "Ocioso" },
        ["Status_Offline"] = new[] { "离线", "Offline", "オフライン", "Offline" },
        ["Status_Paused"] = new[] { "待机", "Standby", "待機", "Em espera" },
        ["Status_Running"] = new[] { "运行", "Running", "稼働中", "Em execução" },
        ["Tab_Alarm"] = new[] { "报警", "Alarm", "警報", "Alarm" },
        ["Tab_Oee"] = new[] { "OEE", "OEE", "OEE", "OEE" },
        ["Tab_Production"] = new[] { "产量", "Production", "生産", "Production" },
        ["Tab_Status"] = new[] { "状态", "Status", "状態", "Status" },
        ["Unit_PerHour"] = new[] { "件/h", "pcs/h", "個/h", "peças/h" },
        ["Val_DynAddr"] = new[] { "动态派生 · :5129", "Auto-derived · :5129", "自動導出 · :5129", "Auto-derived · :5129" },
        ["Val_NoAlarms"] = new[] { "当前无激活报警", "No active alarms", "アクティブ警報なし", "No active alarms" },
        ["Val_NoData"] = new[] { "无数据", "No Data", "データなし", "No Data" },
        ["Val_NoWorkOrder"] = new[] { "暂无工单", "No work orders", "作業指示なし", "No work orders" },
        ["Val_WaitData"] = new[] { "等待数据积累…", "Waiting for data…", "データ蓄積待ち…", "Waiting for data…" },
        ["Wo_Aborted"] = new[] { "已终止", "Aborted", "中止", "Aborted" },
        ["Wo_Completed"] = new[] { "已完成", "Completed", "完了", "Completed" },
        ["Wo_DoneNg"] = new[] { "完成 NG", "Done NG", "完了 NG", "Done NG" },
        ["Wo_DoneOk"] = new[] { "完成 OK", "Done OK", "完了 OK", "Done OK" },
        ["Wo_List"] = new[] { "工单列表", "Work Order List", "工単リスト", "Work Order List" },
        ["Wo_None"] = new[] { "暂无工单", "No work orders", "工単なし", "No work orders" },
        ["Wo_OrderNo"] = new[] { "工单号", "Order No", "工単番号", "Nº do pedido" },
        ["Wo_Pending"] = new[] { "待开始", "Pending", "未開始", "Pending" },
        ["Wo_PlanEnd"] = new[] { "计划结束", "Planned End", "計画終了", "Planned End" },
        ["Wo_PlanQty"] = new[] { "计划量", "Target Qty", "計画数", "Target Qty" },
        ["Wo_PlanStart"] = new[] { "计划开始", "Planned Start", "計画開始", "Planned Start" },
        ["Wo_Product"] = new[] { "产品", "Product", "製品", "Product" },
        ["Wo_Progress"] = new[] { "{0} / {1} 件", "{0} / {1} pcs", "{0} / {1} 個", "{0} / {1} pcs" },
        ["Wo_ProgressPending"] = new[] { "-- / {0} 件", "-- / {0} pcs", "-- / {0} 個", "-- / {0} pcs" },
        ["Wo_Running"] = new[] { "生产中", "In Production", "生産中", "In Production" },
        ["Wo_Status"] = new[] { "状态", "Status", "状態", "Status" },
        ["Wo_Title"] = new[] { "工单管理（只读）", "Work Orders (Read-only)", "工単管理（読み取り専用）", "Work Orders (Read-only)" },
    };
    private static readonly Dictionary<string, int> LanguageIndices = new(StringComparer.OrdinalIgnoreCase)
    {
        ["zh-CN"] = 0,
        ["en-US"] = 1,
        ["ja-JP"] = 2,
        ["pt-BR"] = 3,
    };
    private static readonly string[] LegacyLanguageCodes = ["zh-CN", "en-US", "ja-JP", "pt-BR"];
    private static Dictionary<string, string[]> s_values = Clone(BuiltinD);

    public static IReadOnlyList<string> LanguageCodes => LanguageIndices.Keys.ToArray();
    public const string DefaultLanguage = "zh-CN";
    public static string Current { get; set; } = DefaultLanguage;

    public static bool IsSupportedLanguage(string? language)
        => language is not null && LanguageIndices.ContainsKey(language);

    public static string NormalizeLanguage(string? language)
        => LanguageIndices.Keys.FirstOrDefault(code =>
            string.Equals(code, language, StringComparison.OrdinalIgnoreCase))
            ?? DefaultLanguage;

    /// <summary>把旧版屏端的语言序号转换为动态语言代码。</summary>
    public static string FromLegacyIndex(int index)
    {
        if (index < 0 || index >= LegacyLanguageCodes.Length)
            return DefaultLanguage;
        return IsSupportedLanguage(LegacyLanguageCodes[index])
            ? NormalizeLanguage(LegacyLanguageCodes[index])
            : DefaultLanguage;
    }

    /// <summary>合并 Collector 启动时读取的 WPF 文案覆盖；未知 Web Key 会被忽略。</summary>
    public static void ApplyOverrides(IEnumerable<LocalizationOverrideDto> overrides)
    {
        var values = Clone(BuiltinD);

        foreach (var item in overrides)
        {
            if (!string.Equals(item.Resource, "Wpf", StringComparison.Ordinal)
                || !LanguageIndices.TryGetValue(NormalizeLanguage(item.CultureName), out var languageIndex))
                continue;

            var key = item.Key.StartsWith("Web_", StringComparison.Ordinal)
                ? item.Key[4..]
                : item.Key;
            if (values.TryGetValue(key, out var languageValues)
                && BuiltinD.TryGetValue(key, out var builtinValues)
                && HasCompatibleFormat(builtinValues[languageIndex], item.Value))
                languageValues[languageIndex] = item.Value;
        }
        Interlocked.Exchange(ref s_values, values);
    }

    private static bool HasCompatibleFormat(string expected, string actual)
    {
        if (!TryGetPlaceholderSignature(expected, out var expectedSignature)
            || !TryGetPlaceholderSignature(actual, out var actualSignature)
            || !expectedSignature.OrderBy(pair => pair.Key)
                .SequenceEqual(actualSignature.OrderBy(pair => pair.Key)))
            return false;

        try
        {
            var maxIndex = actualSignature.Keys.DefaultIfEmpty(-1).Max();
            var arguments = Enumerable.Range(0, maxIndex + 1)
                .Select(_ => (object)new FormatProbe())
                .ToArray();
            _ = string.Format(CultureInfo.InvariantCulture, actual, arguments);
            return true;
        }
        catch (FormatException)
        {
            return false;
        }
        catch (ArgumentException)
        {
            return false;
        }
    }

    private static bool TryGetPlaceholderSignature(
        string value,
        out Dictionary<int, int> signature)
    {
        signature = new Dictionary<int, int>();
        var maxIndex = -1;
        for (var index = 0; index < value.Length;)
        {
            if (value[index] == '{')
            {
                if (index + 1 < value.Length && value[index + 1] == '{')
                {
                    index += 2;
                    continue;
                }

                index++;
                var start = index;
                while (index < value.Length && char.IsDigit(value[index])) index++;
                if (start == index || !int.TryParse(value[start..index], out var argumentIndex))
                    return false;
                maxIndex = Math.Max(maxIndex, argumentIndex);

                if (index < value.Length && value[index] == ',')
                {
                    index++;
                    while (index < value.Length && char.IsWhiteSpace(value[index])) index++;
                    if (index < value.Length && value[index] == '-') index++;
                    start = index;
                    while (index < value.Length && char.IsDigit(value[index])) index++;
                    if (start == index) return false;
                    while (index < value.Length && char.IsWhiteSpace(value[index])) index++;
                }

                if (index < value.Length && value[index] == ':')
                {
                    index++;
                    while (index < value.Length && value[index] != '}')
                    {
                        if (value[index] == '{') return false;
                        index++;
                    }
                }

                if (index >= value.Length || value[index] != '}') return false;
                signature[argumentIndex] = signature.TryGetValue(argumentIndex, out var count)
                    ? count + 1
                    : 1;
                index++;
            }
            else if (value[index] == '}')
            {
                if (index + 1 < value.Length && value[index + 1] == '}')
                {
                    index += 2;
                    continue;
                }
                return false;
            }
            else
            {
                index++;
            }
        }
        return maxIndex < 0 || signature.Keys.All(argumentIndex => argumentIndex <= maxIndex);
    }

    private sealed class FormatProbe : IFormattable
    {
        public string ToString(string? format, IFormatProvider? formatProvider) => "x";
        public override string ToString() => "x";
    }

    private static Dictionary<string, string[]> Clone(Dictionary<string, string[]> source)
        => source.ToDictionary(pair => pair.Key, pair => pair.Value.ToArray());

    public static string T(string key, params object[] args)
    {
        var values = Volatile.Read(ref s_values);
        if (values.TryGetValue(key, out var languageValues))
        {
            var languageIndex = LanguageIndices.TryGetValue(Current, out var index) ? index : 0;
            var text = languageValues[languageIndex];
            if (args.Length == 0) return text;
            try
            {
                return string.Format(text, args);
            }
            catch (FormatException)
            {
                return text;
            }
        }
        return key;
    }
}
